### PR TITLE
fix(eds/blockstore): Puts on EDSStore Blockstore

### LINKED ISSUE #2424: eds: Blockstore provided by the Store should support Put
## Context
During the design and implementation of #1099, we missed the necessity of caching the inner and leaf nodes during reconstruction via the Blockservice, leading to Bitswap having no access to them. This is due to [all the Puts being discarded](https://github.com/celestiaorg/celestia-node/blob/main/share/eds/blockstore.go#L88) on the Blockstore.

## Problems
* FNs do not share proofs and data during reconstruction between each other.
* FNs cannot generate BEFPs for withheld blocks. 

## Solution
The proposed solution here is changing Blockstore to support Put operations:
* Blockstore over on-disk Datastore
	* Dagstore's Blockstore would write to disk and, on reads, check the index first and then the Datastore.
	* The default badger Datastore scales well for write-heavy loads, and considering sparse read patterns for reconstruction and BEFP, it should also suit read requirements.
	* The only complication is clean-up, which can be naively solved by iterating over each stored piece with the DeleteBlock method on Blockstore at the end of the reconstruction session(or even after we put an indexed eds to avoid interruption of serving data to other nodes over bitswap)
	
* Blockstore over in-mem Datastore
	* Similar cleanup complication.
	* Similar implementation time estimate as for on-disk
	* Less robust. Does not tolerates restarts.
	
	
## Testing
We have a (flaky) Swamp reconstruction test that asserts that a FN can reconstruct a block from light nodes only, but we also need to add a test similar to the test below, which validates that FNs can collectively rebuild the block.  
https://github.com/celestiaorg/celestia-node/blob/4d986940d662649eba4b0d3daa85268318204ff2/share/availability/full/reconstruction_test.go#L162

Once we know that this works fine in Swamp, we should also replicate the same scenario on TG.

### PR DESCRIPTION
**Pull request by distractedm1nd**
Closes #2424 

Alternative Design Discussions:
- Using in-memory instead of in on disk: During an unexpected shutdown or in the case of AsyncGetter, cleanup would not occur and blocks would be stuck in the store indefinitely. Using an in-memory blockstore would fix this issue upon restarts
-  Using a local Blockgetter to pass to NewErrByzantine: Instead of putting the blocks into the EDS blockstore, the retrieval session could make an in-memory blockstore on the fly to hand to NewErrByzantine when needed. This would look cleaner in the code/make sense architecturally, but it would mean full nodes cannot share these shares with each other during reconstruction.

### CODE REVIEW

**Review by Wondertan — COMMENTED** [review]
> Using an in-memory blockstore would fix this issue upon restarts

Losing all the shares and proofs collected and necessary for reconstruction after an unexpected shutdown. I think we should go with better resilience and availability with a tradeoff of storing a bit more data.

I don't like the current state of cleaning up in Retriever, and I think this is where and why your alternative ideas are coming from. Besides, the current solution is not atomic, and there will be gaps in data availability between the moment of Retriever cleaning up and EDSStore preparing and making all the data on disk available for serves. This hints that cleaning up logic can and should live in the EDSStore itself and be executed right after the EDS is successfully stored. 

As discussed in our standup, I suggest cleaning up logic in a separate PR, greatly simplifying this one and giving us more time to think about various options while still solving the original problem with the consequence of storing copies of rarely reconstructable EDSes.

**Comment by walldiss** [comment]
>Using a local Blockgetter to pass to NewErrByzantine: Instead of putting the blocks into the EDS blockstore, the retrieval session could make an in-memory blockstore on the fly to hand to NewErrByzantine when needed. This would look cleaner in the code/make sense architecturally, but it would mean full nodes cannot share these shares with each other during reconstruction.

This solution will not allow to serve intermediate nodes while block is being sampled, but it is rare case, that has little benefit. All of those needs to happen at the same time for it to give benefit:
- it is only possible, when full node is using ipld sampling, which is very rare.
- Request for intermediate node should happen while sampling is still in process, that is also another rare event.

With all those rarity, it will allow client to sample just a little bit faster, increasing the pool of peers with available blocks, with those that are in the process of sampling.

Downsides:
- On the other hand this change introduces major engineering complexity, related to maintaining and **synchronising** the global state (blockstore). This state needs to be cleared on events, that are not tightly linked and thus do not have ACID properties. It feels there are lot of potential problems with leaked objects, that are forgotten to removed.
-  if items are stored to the disk in the flight, it introduces more write load to the storage, that is already a bottleneck. Given it is very rare read, that is not good utilisation of disk i/o throughput.
- [This important improvement](https://github.com/celestiaorg/celestia-node/issues/2116) will be much harder to implement, unless global state is removed.

Making local blockservice when BEFP happens without implementing globally managed blockstore, will reduce this PR to like 30 lines of code, while losing not much.

**Comment by Wondertan** [comment]
> Yes, this solution will not allow to serve intermediate nodes while block is being sampled, 

> it is only possible, when full node is using ipld sampling, which is very rare.

> Request for intermediate node should happen while sampling is still in process, that is also another rare event.


@walldiss, This is a _strong_ requirement to consider reconstruction finished. It's part of a worst case scenario and security foundation the whole system works on.

cc @musalbas

**Comment by walldiss** [comment]
Also it is worth considering to decompose this issue into 2:
- provide proofs for befp constructor. This is relatively easy, considering there is proofAdder, that contains all proofs to be used to construct befp. 
- allow intermediate nodes cache. This is not easy, so I would suggest to decouple it.

**Comment by Wondertan** [comment]
We agreed to:
* Keep blockstore over on-disk datastore
* Extract cleaning up logic as a separate issue/PR(@distractedm1nd, please do the issue)
	* Where we discuss the cleaning-up strategy
* Implement a benchmark for Retriever running over the production datastore.

File: share/eds/blockstore.go [hunk 1]
```diff
@@ -30,29 +33,46 @@ var (
...
 func (bs *blockstore) Has(ctx context.Context, cid cid.Cid) (bool, error) {
 	keys, err := bs.store.dgstr.ShardsContainingMultihash(ctx, cid.Hash())
-	if errors.Is(err, ErrNotFound) {
-		return false, nil
+	k := dshelp.MultihashToDsKey(cid.Hash())
+	if errors.Is(err, ErrNotFound) || errors.Is(err, ErrNotFoundInIndex) {
+		// key wasn't found in top level blockstore, but could be in datastore while being reconstructed
+		dsHas, dsErr := bs.ds.Has(ctx, k)
+		if dsErr != nil {
+			return false, ErrNotFound
```
[the remark this answers is not in the document]
Comment (distractedm1nd) [reply share/eds/blockstore.go:54]: great catch

**Comment by distractedm1nd** [comment]
After removing cleanup I realized the benchmark doesnt really make sense, I cannot benchmark without introducing an option that disables puts @walldiss , or am I understanding incorrectly?

File: go.mod [hunk 2]
```diff
@@ -81,6 +81,8 @@ require (
 	google.golang.org/protobuf v1.31.0
 )
 
+require github.com/ipfs/go-ipfs-ds-help v1.1.0
```
Comment (Wondertan) [inline go.mod:84]: Separated?

File: share/eds/retriever.go [hunk 3]
```diff
@@ -30,6 +30,10 @@ var (
 	tracer = otel.Tracer("share/eds")
 )
 
+type RetrieverOption func(*Retriever)
+
+type CleanupFunc func(context.Context, cid.Cid) error
+
```
Comment (Wondertan) [inline share/eds/retriever.go:36]: Could you remove it? Because of the atomicity argument, it's not practical to do cleanup in Retriever. Cleaning should happen _only_ after the EDS gets indexed and stored on disk.

File: share/eds/accessor_cache.go [hunk 4]
```diff
@@ -16,7 +16,7 @@ import (
 
 var (
 	defaultCacheSize = 128
-	errCacheMiss     = errors.New("accessor not found in blockstore cache")
+	errCacheMiss     = errors.New("accessor not found in Blockstore cache")
```
Comment (Wondertan) [inline share/eds/accessor_cache.go:19]:
```suggestion
	errCacheMiss     = errors.New("accessor not found in blockstore cache")
```

File: share/eds/accessor_cache.go [hunk 5]
```diff
@@ -114,7 +114,7 @@ func (bc *blockstoreCache) unsafeAdd(
 ) (*accessorWithBlockstore, error) {
 	blockStore, err := accessor.Blockstore()
 	if err != nil {
-		return nil, fmt.Errorf("failed to get blockstore from accessor: %w", err)
+		return nil, fmt.Errorf("failed to get Blockstore from accessor: %w", err)
```
Comment (Wondertan) [inline share/eds/accessor_cache.go:117]:
```suggestion
		return nil, fmt.Errorf("failed to get blockstore from accessor: %w", err)
```

**Review by Wondertan — COMMENTED** [review]
Need to review the test as well

File: share/eds/accessor_cache.go [hunk 6]
```diff
@@ -65,7 +65,7 @@ func (bc *blockstoreCache) evictFn() func(_ interface{}, val interface{}) {
 		if err != nil {
 			log.Errorf("couldn't close accessor after cache eviction: %s", err)
 		}
-		bc.metrics.observeEvicted(err != nil)
```
[the remark this answers is not in the document]
Comment (distractedm1nd) [reply share/eds/accessor_cache.go:68]: oops, probably from rebase

File: go.mod (hunk 2 above)
Comment (distractedm1nd) [reply go.mod:84]: dont know how this happened, only ran go mod tidy

File: share/eds/accessor_cache.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (distractedm1nd) [reply share/eds/accessor_cache.go:68]: wait... have no idea how this happened. probably typed it manually from diff and mixed it up

File: nodebuilder/tests/reconstruct_test.go [hunk 7]
```diff
@@ -81,6 +82,164 @@ func TestFullReconstructFromBridge(t *testing.T) {
...
+Test-Case: Full Node reconstructs blocks from each other, after unsuccessfully syncing the complete
+block from LN subnetworks. Analog to TestShareAvailable_DisconnectedFullNodes.
+*/
+func TestFullReconstructFromFulls(t *testing.T) {
+	light.DefaultSampleAmount = 10 // s
+	const (
+		blocks = 10
+		btime  = time.Millisecond * 300
+		bsize  = 8  // k
+		lnodes = 12 // c - total number of nodes on two subnetworks
```
Comment (Wondertan) [inline nodebuilder/tests/reconstruct_test.go:95]: How much more time higher param take?

**Review by Wondertan — COMMENTED** [review]
Test LGTM

Has conflicts

File: nodebuilder/tests/reconstruct_test.go (hunk 7 above)
Comment (distractedm1nd) [reply nodebuilder/tests/reconstruct_test.go:95]: I couldn't get it to pass with the other parameters, so we decided we should test this scenario in TG and have the swamp be this mild version - since avail tests already show its possible with the other parameter set anyways

File: share/eds/retriever.go [hunk 8]
```diff
@@ -120,8 +120,11 @@ type retrievalSession struct {
 }
 
 // newSession creates a new retrieval session and kicks off requesting process.
-func (r *Retriever) newSession(ctx context.Context, dah *da.DataAvailabilityHeader) (*retrievalSession, error) {
+func (r *Retriever) newSession(
+	ctx context.Context, dah *da.DataAvailabilityHeader,
+) (*retrievalSession, error) {
```
[the remark this answers is not in the document]
Comment (distractedm1nd) [reply share/eds/retriever.go:125]: Ah. This was because I changed the signature and changed it back, will fix

File: nodebuilder/tests/reconstruct_test.go (hunk 7 above)
Comment (distractedm1nd) [reply nodebuilder/tests/reconstruct_test.go:95]: For clarification, I am convinced the only reason the other swamp tests work with so many light nodes is because the parameters ensure a very high share redundancy. The shares are available from many sources

Comment (Wondertan) [reply nodebuilder/tests/reconstruct_test.go:95]: avail tests made me think of diff avail first : )

File: go.mod [hunk 9]
```diff
@@ -80,6 +80,8 @@ require (
...
```
Comment (Wondertan) [inline go.mod:83]: Again :sob:

**Review by Wondertan — DISMISSED** [review]

File: go.mod (hunk 9 above)
Comment (distractedm1nd) [reply go.mod:83]: go mod tidy is doing this. will fix

**Comment by Wondertan** [comment]
Snyk is complaining for some unknown reason

File: share/eds/blockstore.go [hunk 10]
```diff
@@ -75,27 +97,35 @@ func (bs *blockstore) GetSize(ctx context.Context, cid cid.Cid) (int, error) {
...
 
-// PutMany is a noop on the EDS blockstore, but it does not return an error because it is called by
-// bitswap. For clarification, an implementation of PutMany does not make sense in this context
-// because it is unclear which CAR file the blocks should be written to.
-//
-// TODO: throw errUnsupportedOperation after issue #1440
-func (bs *blockstore) PutMany(context.Context, []blocks.Block) error {
-	return nil
+func (bs *blockstore) PutMany(ctx context.Context, blocks []blocks.Block) error {
+	if len(blocks) == 1 {
```
Comment (renaynay) [inline share/eds/blockstore.go:112]: could PutMany ever get called on len 0? If so, should we short circuit before?

File: share/eds/inverted_index.go [hunk 11]
```diff
@@ -14,6 +15,9 @@ import (
 
 const invertedIndexPath = "/inverted_index/"
 
+// ErrNotFoundInIndex is returned instead of ErrNotFound if the multihash doesn't exist in the index
+var ErrNotFoundInIndex = fmt.Errorf("failed to lookup index")
```
Comment (renaynay) [inline share/eds/inverted_index.go:19]: this error message is confusing - shouldn't it be "does not exist in index" then?

File: nodebuilder/tests/reconstruct_test.go [hunk 12]
```diff
@@ -81,6 +82,164 @@ func TestFullReconstructFromBridge(t *testing.T) {
...
+	)
+
+	ctx, cancel := context.WithTimeout(context.Background(), swamp.DefaultTestTimeout)
+	t.Cleanup(cancel)
+
+	sw := swamp.NewSwamp(t, swamp.WithBlockTime(btime))
+	fillDn := swamp.FillBlocks(ctx, sw.ClientContext, sw.Accounts, bsize, blocks)
+
+	const defaultTimeInterval = time.Second * 5
+	cfg := nodebuilder.DefaultConfig(node.Bridge)
```
Comment (renaynay) [inline nodebuilder/tests/reconstruct_test.go:105]: you never actually use this config.

File: nodebuilder/tests/reconstruct_test.go [hunk 13]
```diff
@@ -81,6 +82,164 @@ func TestFullReconstructFromBridge(t *testing.T) {
...
+	cfg.Share.Discovery.PeersLimit = 0
+	setTimeInterval(cfg, defaultTimeInterval)
+	bridge := sw.NewBridgeNode()
+	addrsBridge, err := peer.AddrInfoToP2pAddrs(host.InfoFromHost(bridge.Host))
```
Comment (renaynay) [inline nodebuilder/tests/reconstruct_test.go:109]: you don't need to extract this, check how `swamp.SetBootstrapper` works

File: nodebuilder/tests/reconstruct_test.go [hunk 14]
```diff
@@ -81,6 +82,164 @@ func TestFullReconstructFromBridge(t *testing.T) {
...
+				return err
+			}
+			subs[i] = sub
+			lights1[i] = light
+			return light.Start(errCtx)
+		})
+		errg.Go(func() error {
+			lnConfig := nodebuilder.DefaultConfig(node.Light)
+			setTimeInterval(lnConfig, defaultTimeInterval)
+			lnConfig.Header.TrustedPeers = append(lnConfig.Header.TrustedPeers, addrsBridge[0].String())
```
Comment (renaynay) [inline nodebuilder/tests/reconstruct_test.go:142]: unnecessary, check sw.SetBootstrapper

File: nodebuilder/tests/reconstruct_test.go [hunk 15]
```diff
@@ -81,6 +82,164 @@ func TestFullReconstructFromBridge(t *testing.T) {
...
+	})
+	require.Error(t, errg.Wait())
+	cancelErr()
+
+	// Reconnect FNs
+	sw.Connect(t, full1, full2)
+
+	errg, bctx := errgroup.WithContext(ctx)
+	for i := 10; i < blocks+11; i++ {
+		i := i
```
Comment (renaynay) [inline nodebuilder/tests/reconstruct_test.go:228]: do we still need to do this on 1.21? also i don't think you need to do this in general

File: share/eds/blockstore.go (hunk 10 above)
Comment (distractedm1nd) [reply share/eds/blockstore.go:112]: Yes, good catch

File: nodebuilder/tests/reconstruct_test.go (hunk 15 above)
Comment (distractedm1nd) [reply nodebuilder/tests/reconstruct_test.go:228]: I'll check

Comment (distractedm1nd) [reply nodebuilder/tests/reconstruct_test.go:228]: can't do it yet - we'd have to build with a GOEXPERIMENT flag

File: share/eds/blockstore.go [hunk 16]
```diff
@@ -30,29 +33,43 @@ var (
...
 		cache: cache,
+		ds:    namespace.Wrap(ds, blockstoreCacheKey),
 	}
 }
 
 func (bs *blockstore) Has(ctx context.Context, cid cid.Cid) (bool, error) {
 	keys, err := bs.store.dgstr.ShardsContainingMultihash(ctx, cid.Hash())
-	if errors.Is(err, ErrNotFound) {
-		return false, nil
+	k := dshelp.MultihashToDsKey(cid.Hash())
```
[the remark this answers is not in the document]
Comment (distractedm1nd) [reply share/eds/blockstore.go:49]: replacing w inline here because it is separated, but not inlining when directly above Get call because it is easier to read (less nested) and the compiler makes this optimization anyways

File: nodebuilder/tests/reconstruct_test.go (hunk 15 above)
Comment (renaynay) [reply nodebuilder/tests/reconstruct_test.go:221]: regardless you're not passing this var into a routine so why copy?

**Comment by renaynay** [comment]
BTW @vgonkivs rebased BEFP tests on this PR and they pass 🙏🏻

**Review by vgonkivs — APPROVED** [review]
LGTM
