### PR TITLE
fix(ipld): fix reconstruction by re-enabling re-importing of rsmt2d.ExtendedDataSquare

### LINKED ISSUE #787: flaky TestSharesAvailable_Full
image

### PR DESCRIPTION
**Pull request by Wondertan**
An update of rsmt2d happened in https://github.com/celestiaorg/celestia-node/pull/737 during Mamaki launch preparation. This update changed our code not to reimport the square on each reconstruction attempt which silently sneaked in the problem, which is not reproducible with current tests. Reconstruction tests(#702) reproduce it, but they are not yet merged.

I was able to change the code to reproduce it reliably. Mainly I had to fetch only from columns and force the code to download only [2:4) quadrants. Unfortunately, it is hard to extract the reproducible case in a separate test, so we can either rely on reconstruction tests that are soon to be merged, or I can still try to make a test.

The reason for the bug is explained in #787, as well as a cleaner way to fix it. 
Closes #787

P.S. Was pretty hard to debug this case. I went on the wrong paths like 3 times. Though collected some minor findings that I am going to submit further.

### CODE REVIEW

**Review by liamsi — APPROVED** [review]
I would really, really prefer a testcase for this but I trust your hours of debugging this.

**Review by vgonkivs — APPROVED** [review]

**Comment by Wondertan** [comment]
Force push with a cleaner commit

File: ipld/retriever.go [hunk 1]
```diff
@@ -151,6 +151,19 @@ func (rs *retrievalSession) Reconstruct() (*rsmt2d.ExtendedDataSquare, error) {
 	// prevent further writes to the square
 	rs.squareLk.Lock()
 	defer rs.squareLk.Unlock()
+
+	// TODO(@Wondertan): This is bad!
+	//  * We should not reimport the square multiple times
+	//  * We should set shares into imported square via SetShare(https://github.com/celestiaorg/rsmt2d/issues/83)
```
Comment (adlerjohn) [inline ipld/retriever.go:157]: It's not clear to me how specifically this fixes a bug. This is indicative of a bug in the rsmt2d, not a missing feature.

**Comment by Wondertan** [comment]
@liamsi, I added a test anyway. You can try removing the fix commit and reproduce it yourself. Sometimes it fails with other rsmt2d errors besides byzantine. The test ensures that at least 2 more quadrants are fetching besides the initial one, and all of those written into the shared square, and somewhere in between, the reconstruction fails.

**Comment by Wondertan** [comment]
As always on CI something goes not like locally, aaaaa

**Comment by Wondertan** [comment]
Force push with an updated test that should fail on CI, lets see...

**Comment by Wondertan** [comment]
Ok, test is fixed

**Review by adlerjohn — APPROVED** [review]

File: ipld/retriever_test.go [hunk 2]
```diff
@@ -94,3 +94,33 @@ func TestRetriever_ByzantineError(t *testing.T) {
 	var errByz *ErrByzantine
 	require.ErrorAs(t, err, &errByz)
 }
+
+// TestRetriever_MultipleRandQuadrants asserts that reconstruction succeeds
+// when any three random quadrants requested.
+func TestRetriever_MultipleRandQuadrants(t *testing.T) {
+	RetrieveQuadrantTimeout = time.Millisecond * 500
```
Comment (liamsi) [inline ipld/retriever_test.go:101]: If this global var is used in multiple tests, this assignment here will have side-effects.

Comment (Wondertan) [reply ipld/retriever_test.go:101]: Yeah, but I am controlling that. We have https://github.com/celestiaorg/celestia-node/issues/709 to fix this.
