### PR TITLE
fix: jwt token nonce and expiration time

### LINKED ISSUE #2420: libs: Add expiry for JWT
Add expiration to JWT generation

### PR DESCRIPTION
**Pull request by cristaloleg**
Fixes #2420

### CODE REVIEW

File: api/rpc/perms/permissions.go [hunk 1]
```diff
@@ -28,9 +32,16 @@ func (j *JWTPayload) MarshalBinary() (data []byte, err error) {
...
+	var nonce [32]byte
+	if _, err := rand.Read(nonce[:]); err != nil {
+		return nil, err
+	}
+
 	p := &JWTPayload{
-		Allow: perms,
+		Allow:     perms,
+		Nonce:     nonce[:],
+		ExpiresAt: time.Now().UTC().Add(ttl),
```
Comment (cristaloleg) [inline api/rpc/perms/permissions.go:44]: `.UTC()` to prevent timezone issues.

File: api/rpc_test.go [hunk 2]
```diff
@@ -59,7 +59,7 @@ func TestRPCCallsUnderlyingNode(t *testing.T) {
 	nd, server := setupNodeWithAuthedRPC(t, signer, verifier)
 	url := nd.RPCServer.ListenAddr()
 
-	adminToken, err := perms.NewTokenWithPerms(signer, perms.AllPerms)
+	adminToken, err := perms.NewTokenWithPerms(signer, perms.AllPerms, time.Minute)
```
Comment (cristaloleg) [inline api/rpc_test.go:62]: Should be fine for the test.

File: cmd/auth.go [hunk 3]
```diff
@@ -34,6 +35,11 @@ func AuthCmd(fsets ...*flag.FlagSet) *cobra.Command {
 				return err
 			}
 
+			ttl, err := cmd.Flags().GetDuration("ttl")
```
Comment (cristaloleg) [inline cmd/auth.go:38]: Should we have a big default here or require a well-defined value all the time?

File: cmd/rpc.go [hunk 4]
```diff
@@ -128,7 +128,7 @@ func getToken(path string) (string, error) {
 		fmt.Printf("error getting the JWT secret: %v", err)
 		return "", err
 	}
-	return buildJWTToken(key.Body, perms.AllPerms)
+	return buildJWTToken(key.Body, perms.AllPerms, time.Minute)
```
Comment (cristaloleg) [inline cmd/rpc.go:131]: Fine for rpc, I think?

File: nodebuilder/node/cmd/node.go [hunk 5]
```diff
@@ -99,7 +99,12 @@ var authCmd = &cobra.Command{
 			perms[i] = (auth.Permission)(p)
 		}
 
-		result, err := client.Node.AuthNew(c.Context(), perms)
+		ttl, err := cmd.Flags().GetDuration("ttl")
```
Comment (cristaloleg) [inline nodebuilder/node/cmd/node.go:102]: Same here, do we need a default value or require all the time?

File: nodebuilder/node/cmd/node.go [hunk 6]
```diff
@@ -87,8 +87,8 @@ var authCmd = &cobra.Command{
 	Use:   "set-permissions",
 	Args:  cobra.MinimumNArgs(1),
 	Short: "Signs and returns a new token with the given permissions.",
-	RunE: func(c *cobra.Command, args []string) error {
-		client, err := cmdnode.ParseClientFromCtx(c.Context())
+	RunE: func(cmd *cobra.Command, args []string) error {
```
Comment (cristaloleg) [inline nodebuilder/node/cmd/node.go:90]: Rename for consistency with other usages.

File: libs/authtoken/authtoken.go [hunk 7]
```diff
@@ -17,17 +20,27 @@ func ExtractSignedPermissions(verifier jwt.Verifier, token string) ([]auth.Permi
 		return nil, err
 	}
 	p := new(perms.JWTPayload)
-	err = json.Unmarshal(tk.Claims(), p)
-	if err != nil {
+
+	if err := json.Unmarshal(tk.Claims(), p); err != nil {
 		return nil, err
 	}
+	if p.ExpiresAt.Before(time.Now().UTC()) {
```
Comment (cristaloleg) [inline libs/authtoken/authtoken.go:27]: AFAIK that's the only place where we need to validate time.

File: cmd/auth.go (hunk 3 above)
Comment (vgonkivs) [reply cmd/auth.go:38]: Id short-circuit immediately if TTL is not passed. I don't see any reason why we should pick TTL for the user.

File: api/rpc/perms/permissions.go (hunk 1 above)
Comment (renaynay) [reply api/rpc/perms/permissions.go:44]: @cristaloleg let's please only add a TTL if one is specified. I think we should preserve the default behaviour which is token is eternal.

File: api/rpc_test.go (hunk 2 above)
Comment (renaynay) [reply api/rpc_test.go:62]: Can you also add test where token is valid for some time, then is invalid after expiry? I know it's time-based so it's tricky but would be nice to have that coverage.

File: cmd/auth.go (hunk 3 above)
Comment (renaynay) [reply cmd/auth.go:38]: + to slava's comment. We should not set a TTL - our default should be that the key is eternal unless TTL is specified.

File: api/rpc/perms/permissions.go [hunk 8]
```diff
@@ -28,9 +32,16 @@ func (j *JWTPayload) MarshalBinary() (data []byte, err error) {
 
 // NewTokenWithPerms generates and signs a new JWT token with the given secret
 // and given permissions.
-func NewTokenWithPerms(signer jwt.Signer, perms []auth.Permission) ([]byte, error) {
+func NewTokenWithPerms(signer jwt.Signer, perms []auth.Permission, ttl time.Duration) ([]byte, error) {
+	var nonce [32]byte
```
Comment (walldiss) [inline api/rpc/perms/permissions.go:36]: Is there particular reason to use fixed sized array here? if slice is used instead of array it will remove convertions by [:]

File: cmd/rpc.go (hunk 4 above)
Comment (renaynay) [reply cmd/rpc.go:131]: No actually, users usually use rpc cli locally or for debugging, I don't think auth token should expire for those purposes. Let's pls leave default behaviour.

File: nodebuilder/node/node.go [hunk 9]
```diff
@@ -23,18 +24,18 @@ type Module interface {
 	// AuthVerify returns the permissions assigned to the given token.
 	AuthVerify(ctx context.Context, token string) ([]auth.Permission, error)
 	// AuthNew signs and returns a new token with the given permissions.
-	AuthNew(ctx context.Context, perms []auth.Permission) (string, error)
+	AuthNew(ctx context.Context, perms []auth.Permission, ttl time.Duration) (string, error)
```
[the remark this answers is not in the document]
Comment (renaynay) [reply nodebuilder/node/node.go:27]: Let's pls avoid break in this

File: cmd/auth.go (hunk 3 above)
Comment (walldiss) [reply cmd/auth.go:38]: Force them to pass, so they know when to expect expiry

File: nodebuilder/node/node.go [hunk 10]
```diff
@@ -23,18 +24,18 @@ type Module interface {
...
-		Info        func(context.Context) (Info, error)                                `perm:"admin"`
-		Ready       func(context.Context) (bool, error)                                `perm:"read"`
-		LogLevelSet func(ctx context.Context, name, level string) error                `perm:"admin"`
-		AuthVerify  func(ctx context.Context, token string) ([]auth.Permission, error) `perm:"admin"`
-		AuthNew     func(ctx context.Context, perms []auth.Permission) (string, error) `perm:"admin"`
+		Info        func(context.Context) (Info, error)                                                   `perm:"admin"`
+		Ready       func(context.Context) (bool, error)                                                   `perm:"read"`
+		LogLevelSet func(ctx context.Context, name, level string) error                                   `perm:"admin"`
+		AuthVerify  func(ctx context.Context, token string) ([]auth.Permission, error)                    `perm:"admin"`
+		AuthNew     func(ctx context.Context, perms []auth.Permission, ttl time.Duration) (string, error) `perm:"admin"`
```
Comment (walldiss) [inline nodebuilder/node/node.go:38]: API break, need to update PR description

File: api/rpc/perms/permissions.go (hunk 1 above)
Comment (cristaloleg) [reply api/rpc/perms/permissions.go]: Done

File: libs/authtoken/authtoken.go [hunk 11]
```diff
@@ -17,17 +20,27 @@ func ExtractSignedPermissions(verifier jwt.Verifier, token string) ([]auth.Permi
...
+	var nonce [32]byte
+	if _, err := rand.Read(nonce[:]); err != nil {
+		return "", err
+	}
+
 	token, err := jwt.NewBuilder(signer).Build(&perms.JWTPayload{
-		Allow: permissions,
+		Allow:     permissions,
+		Nonce:     nonce[:],
+		ExpiresAt: time.Now().UTC().Add(ttl),
```
[the remark this answers is not in the document]
Comment (cristaloleg) [reply libs/authtoken/authtoken.go]: Done

File: libs/authtoken/authtoken.go [hunk 12]
```diff
@@ -17,17 +20,27 @@ func ExtractSignedPermissions(verifier jwt.Verifier, token string) ([]auth.Permi
...
 	}
 	p := new(perms.JWTPayload)
-	err = json.Unmarshal(tk.Claims(), p)
-	if err != nil {
+
+	if err := json.Unmarshal(tk.Claims(), p); err != nil {
 		return nil, err
 	}
+	if p.ExpiresAt.Before(time.Now().UTC()) {
+		return nil, fmt.Errorf("token expired %s ago", time.Since(p.ExpiresAt))
```
[the remark this answers is not in the document]
Comment (cristaloleg) [reply libs/authtoken/authtoken.go:28]: `time.Duration` has `.String()` method, are you talking about that? https://pkg.go.dev/time#Duration.String

File: nodebuilder/node/node.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (cristaloleg) [reply nodebuilder/node/node.go]: Done, have added a new method

File: api/rpc/perms/permissions.go (hunk 8 above)
Comment (cristaloleg) [reply api/rpc/perms/permissions.go]: ok, fixed.

File: nodebuilder/node/node.go (hunk 10 above)
Comment (cristaloleg) [reply nodebuilder/node/node.go]: Reverted

File: api/rpc/perms/permissions.go [hunk 13]
```diff
@@ -28,9 +32,21 @@ func (j *JWTPayload) MarshalBinary() (data []byte, err error) {
 
 // NewTokenWithPerms generates and signs a new JWT token with the given secret
 // and given permissions.
-func NewTokenWithPerms(signer jwt.Signer, perms []auth.Permission) ([]byte, error) {
+func NewTokenWithPerms(signer jwt.Signer, perms []auth.Permission, ttl time.Duration) ([]byte, error) {
```
Comment (renaynay) [inline api/rpc/perms/permissions.go:35]: ok sorry missed this one but can you make a separate public method that allows for setting ttl and make this `NewTokenWithPerms` rely on it and not set a TTL ? 

so `NewTokenWithPerms` and `NewTokenWithTTL`

File: api/rpc_test.go [hunk 14]
```diff
@@ -89,6 +89,42 @@ func TestRPCCallsUnderlyingNode(t *testing.T) {
...
+		if err == nil {
+			t.Cleanup(rpcClient.Close)
+			break
+		}
+	}
+	require.NotNil(t, rpcClient)
+	require.NoError(t, err)
+
+	_, err = rpcClient.State.Balance(ctx)
+	require.Error(t, err, err)
```
Comment (renaynay) [inline api/rpc_test.go:125]: pls assert err is == smth or contains somth

File: cmd/rpc.go (hunk 4 above)
Comment (renaynay) [reply cmd/rpc.go:131]: needs addressing pls - let's not set expiry here.

File: libs/authtoken/authtoken.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (renaynay) [reply libs/authtoken/authtoken.go:28]: Yes

File: cmd/auth.go [hunk 15]
```diff
@@ -34,6 +35,8 @@ func AuthCmd(fsets ...*flag.FlagSet) *cobra.Command {
 				return err
 			}
 
+			ttl, _ := cmd.Flags().GetDuration("ttl")
```
Comment (renaynay) [inline cmd/auth.go:38]: does this add `--ttl` to the flagset for the auth cmd? also if no `--ttl` is passed then the default for an unchanged/nil Duration == 0? Can we make explicit pls

File: api/rpc_test.go (hunk 14 above)
Comment (cristaloleg) [reply api/rpc_test.go]: My bad, fixed.

File: api/rpc/perms/permissions.go (hunk 13 above)
Comment (cristaloleg) [reply api/rpc/perms/permissions.go]: Ah, okay. Now it clear. Have added a separate function with TTL.

File: cmd/auth.go (hunk 15 above)
Comment (cristaloleg) [reply cmd/auth.go:38]: I'm not `cobra` expert. If you know this part better, please make a push.

File: libs/authtoken/authtoken.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (cristaloleg) [reply libs/authtoken/authtoken.go:28]: It will be used automatically due to `%s` so we are safe here.

File: api/rpc/perms/permissions.go [hunk 16]
```diff
@@ -32,7 +32,26 @@ func (j *JWTPayload) MarshalBinary() (data []byte, err error) {
...
+
+	p := &JWTPayload{
+		Allow: perms,
+		Nonce: nonce,
+	}
+	token, err := jwt.NewBuilder(signer).Build(p)
+	if err != nil {
+		return nil, err
+	}
+	return token.Bytes(), nil
```
Comment (renaynay) [inline api/rpc/perms/permissions.go:49]: nit but this can use NewTokenWithTTL and just not set TTL

**Review by renaynay — APPROVED** [review]
tested manually as well 

`auth` cmd only has `--ttl` flag so it's not a global flag. If it is not passed, ttl will be set to 0, disabling the TTL on the token (so it's eternal).

This PR preserves old behaviour but allows for TTLs on the tokens and also makes the token generated non-deterministic per secret.

**Review by vgonkivs — APPROVED** [review]
