### PR TITLE
swamp/discovery: fix flakiness in restart node discovery test

### LINKED ISSUE #963: test: flakiness TestRestartNodeDiscovery

### PR DESCRIPTION
**Pull request by vgonkivs**
Resolves #963

Root cause: pubsub was restoring the connection between the nodes, so we didn't get the disconnect event as expected.

https://github.com/libp2p/go-libp2p-pubsub/blob/60cf38003244a277084c6f3eec0e584ab6cc07bd/pubsub.go#L710

### CODE REVIEW

File: node/tests/p2p_test.go [hunk 1]
```diff
@@ -188,42 +188,51 @@ func TestRestartNodeDiscovery(t *testing.T) {
...
 	// create one more node with disabled discovery
 	nodesConfig[1] = node.WithPeersLimit(0)
 	node := sw.NewFullNode(nodesConfig...)
+	connectSub, err := nodes[0].Host.EventBus().Subscribe(&event.EvtPeerConnectednessChanged{})
+	require.NoError(t, err)
+	defer connectSub.Close()
+
+	// disconnect and unlink peers in order to receive disconnected event
+	// NOTE: Consistence is very important here. We have to unlink peers and only after that call disconnect
+	// otherwise pubsub could re-establish the connection.
```
Comment (Wondertan) [inline node/tests/p2p_test.go:218]:
```suggestion
	// NOTE: Order is very important here. We have to unlink peers, and only after that call disconnect,
	// otherwise pubsub could re-establish the connection.
```

File: node/tests/p2p_test.go [hunk 2]
```diff
@@ -188,42 +188,51 @@ func TestRestartNodeDiscovery(t *testing.T) {
 		nodes[index] = sw.NewFullNode(nodesConfig...)
 	}
 
-	sub, err := nodes[0].Host.EventBus().Subscribe(&event.EvtPeerConnectednessChanged{})
+	identitySub, err := nodes[0].Host.EventBus().Subscribe(&event.EvtPeerIdentificationCompleted{})
```
Comment (Wondertan) [inline node/tests/p2p_test.go:191]: Don't really get the reasoning behind moving to the Identification event. I know we do those header/p2p tests, but still, I am curious if this change really does anything

**Review by Wondertan — APPROVED** [review]

**Review by renaynay — APPROVED** [review]
utACK and +1 to hlib's comments

File: node/tests/p2p_test.go (hunk 2 above)
Comment (vgonkivs) [reply node/tests/p2p_test.go:191]: Good question. As per implementation `event.EvtPeerIdentificationCompleted` is emitting when identification of a remote peer is done and also its' done *after* `event.EvtPeerConnectednessChanged`. So, by changing EvtPeerConnectednessChanged to EvtPeerIdentificationCompleted I want:

1) to be 100% sure that connection between peers works smoothly;
2) to give more time for schedular to process waiting goroutines(I hope it helps to avoid adding time.Sleep in test);
3) Avoid using for loop because EvtPeerConnectednessChanged could be received more the once(with different peer.IDs).
