### PR TITLE
fix(core): change fill block mode

### LINKED ISSUE #3871: Flaky TestExchange_DoNotStoreHistoric
### Implementation ideas

Unit test is flaky with and occasionally fails with error:
```
Received unexpected error: deliverTxSub was cancelled (reason: CometBFT exited)
```

### PR DESCRIPTION
**Pull request by cristaloleg**
Fixes #3871

### CODE REVIEW

File: core/exchange_test.go [hunk 1]
```diff
@@ -135,7 +135,7 @@ func fillBlocks(
 		default:
 		}
 
-		_, err := cctx.FillBlock(16, cfg.Genesis.Accounts()[0].Name, flags.BroadcastBlock)
```
Comment (cristaloleg) [inline core/exchange_test.go:138]: Deprecated mode

**Review by vgonkivs — APPROVED** [review]

**Review by Wondertan — APPROVED** [review]
