### PR TITLE
fix(header): Extend `ValidateBasic` on `ExtendedHeader` to include data root check

### LINKED ISSUE #1362: header:  `ExtendedHeader`'s `ValidateBasic` must check if the `DAH.Hash()` matches `DataHash` in `RawHeader`

### PR DESCRIPTION
**Pull request by renaynay**
Resolves #1362

### CODE REVIEW

**Review by vgonkivs — DISMISSED** [review]

File: header/testing.go [hunk 1]
```diff
@@ -171,15 +177,15 @@ func RandExtendedHeader(t *testing.T) *ExtendedHeader {
 }
 
 // RandRawHeader provides a RawHeader fixture.
-func RandRawHeader(t *testing.T) *RawHeader {
+func RandRawHeader(t *testing.T, dataHash []byte) *RawHeader {
```
Comment (Wondertan) [inline header/testing.go:180]: nit: `RandRawHeader` is meant to really be rand, so it can be used in tests that don't care about data hashes or other fields. This change makes `RandRawHeader` more oriented toward data testing, thus making it not credibly neutral :joy:, so I would just set DataHash field on the returned RawHeader instead.

Comment (Wondertan) [reply header/testing.go:180]: In this PR in `TestSuites`'s `GenRawHeader` we pass the dataHash and then assign its field another time btw

File: header/header_test.go [hunk 2]
```diff
@@ -36,3 +39,33 @@ func TestMakeExtendedHeaderForEmptyBlock(t *testing.T) {
...
+	sub, err := fetcher.SubscribeNewBlockEvent(ctx)
+	require.NoError(t, err)
+	<-sub
+
+	height := int64(1)
+	b, err := fetcher.GetBlock(ctx, &height)
+	require.NoError(t, err)
+
+	comm, val, err := fetcher.GetBlockInfo(ctx, &height)
+	require.NoError(t, err)
```
Comment (Wondertan) [inline header/header_test.go:61]: simplification: If the goal is to unit test the new check, then all this setup is not necessary. We can use TestSute which is simpler and generates a valid header and we can similarly augment it with an incorrect hash to see that error happens.

Comment (renaynay) [reply header/header_test.go:61]: done.

File: header/testing.go (hunk 1 above)
Comment (renaynay) [reply header/testing.go]: ok

**Review by Wondertan — APPROVED** [review]
