### PR TITLE
fix(gateway): switch to separate Listen/Serve

### LINKED ISSUE #1286: feat(rpc/gateway): move to ListenAndServe
We can use `ListenAndServe`, and get rid of the `listener` on the `Server` structs in gateway+rpc ~~by creating a new constructor that overrides the http server. Using ListenAndServe alone does not allow us to use port 0 in tests without losing the port that gets assigned. @walldiss pointed out we can create a new constructor and pass in a server from the `httptest` package.~~

        Update the server to not use Listener and make lifecycling over HTTP Server directly

_Originally posted by @Wondertan in https://github.com/celestiaorg/celestia-node/pull/1199#discussion_r1006542803_

### PR DESCRIPTION
**Pull request by distractedm1nd**
Closes #1286

This is mainly a fix for test flakiness.

### CODE REVIEW

File: api/gateway/server.go [hunk 1]
```diff
@@ -88,5 +80,5 @@ func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 
 // ListenAddr returns the listen address of the server.
 func (s *Server) ListenAddr() string {
-	return s.listener.Addr().String()
+	return s.srv.Addr
```
Comment (renaynay) [inline api/gateway/server.go:83]: does this give you the full addr + port

**Review by renaynay — APPROVED** [review]

**Comment by distractedm1nd** [comment]
Also is a part of #1306

File: api/rpc_test.go [hunk 2]
```diff
@@ -118,14 +131,15 @@ func setupNodeWithModifiedRPC(t *testing.T) (*nodebuilder.Node, *mockAPI) {
 		dasMock.NewMockModule(ctrl),
 	}
 
-	overrideRPCHandler := fx.Invoke(func(srv *rpc.Server) {
+	// given the behavior of fx.Invoke, this invoke will be called last as it is outside a module
```
Comment (renaynay) [inline api/rpc_test.go:134]:
```suggestion
	// given the behavior of fx.Invoke, this invoke will be called last as it is added at the root level module. For further information, check the documentation on fx.Invoke.
```

**Review by renaynay — APPROVED** [review]

File: api/rpc_test.go (hunk 2 above)
Comment (renaynay) [reply api/rpc_test.go:134]: [blocking] ❤️

**Comment by walldiss** [comment]
Do we still consider moving or rpc test infra to `httptest.Server` in future?

File: api/rpc_test.go [hunk 3]
```diff
@@ -28,9 +29,21 @@ func TestRPCCallsUnderlyingNode(t *testing.T) {
...
 	nd, server := setupNodeWithModifiedRPC(t)
 	url := nd.RPCServer.ListenAddr()
-	client, err := client.NewClient(context.Background(), "http://"+url)
-	t.Cleanup(client.Close)
+	// we need to run this a few times to prevent the race where the server is not yet started
+	var (
+		rpcClient *client.Client
+		err       error
+	)
+	for i := 0; i < 3; i++ {
```
Comment (MSevey) [inline api/rpc_test.go:37]: [non blocking]
This type of retry is really useful in testing. Since it seems like we don't have a helper function for this, we should create one like so, maybe in a `test` package:

```go

// Retry will call 'fn' 'tries' times, waiting 'durationBetweenAttempts'
// between each attempt, returning 'nil' the first time that 'fn' returns nil.
// If 'nil' is never returned, then the final error returned by 'fn' is
// returned.
func Retry(tries int, durationBetweenAttempts time.Duration, fn func() error) (err error) {
	for i := 1; i < tries; i++ {
		err = fn()
		if err == nil {
			return nil
		}
		time.Sleep(durationBetweenAttempts)
	}
	return fn()
}
```

Then this example would turn into:
```go
	err = test.Retry(3, time.Second, func() error {
		return client.NewClient(ctx, "http://"+url)
	})
	require.NoError(t, err)
```

File: nodebuilder/testing.go [hunk 4]
```diff
@@ -46,7 +48,9 @@ func TestNodeWithConfig(t *testing.T, tp node.Type, cfg *Config, opts ...fx.Opti
 	require.NoError(t, err)
 	cfg.Core.IP = ip
 	cfg.Core.RPCPort = port
-	cfg.RPC.Port = "26655"
+	freePort, err := tennet.GetFreePort()
```
Comment (Wondertan) [inline nodebuilder/testing.go:51]: As discussed, we go with 0 rather than this. #1322

**Review by Wondertan — CHANGES_REQUESTED** [review]

File: api/rpc_test.go (hunk 3 above)
Comment (distractedm1nd) [reply api/rpc_test.go:37]: #1332

**Comment by distractedm1nd** [comment]
Now closes #1322 . Deprecates #1286 .

File: nodebuilder/testing.go (hunk 4 above)
Comment (distractedm1nd) [reply nodebuilder/testing.go:51]: done

**Review by Wondertan — APPROVED** [review]
LGTM

**Review by renaynay — APPROVED** [review]

**Review by Wondertan — APPROVED** [review]
