### PR TITLE
fix(blob/service): return error from GetProof if it appears

### LINKED ISSUE #3726: blob: Service.GetProof mistakenly swallows up error from Service.retrieve
If we examine this code https://github.com/celestiaorg/celestia-node/blob/1a1286f454c1dd670af856153a8fc8674cd91192/blob/service.go#L237-L238 we can see something peculiar there that err is set but down below, there is a `return proof, nil` of which due to the use of named returns in Go, even if there was a variable name clash. Please return that value and test that code more: if it was intended, please document it instead.

/cc @liamsi @rootulp @musalbas

### PR DESCRIPTION
**Pull request by vgonkivs**
Resolves #3726

### CODE REVIEW

File: blob/service.go [hunk 1]
```diff
@@ -235,7 +235,7 @@ func (s *Service) GetProof(
 	}}
 
 	_, proof, err = s.retrieve(ctx, height, namespace, sharesParser)
-	return proof, nil
```
Comment (cristaloleg) [inline blob/service.go:238]: nononon, no bare return please 😢

Comment (vgonkivs) [reply blob/service.go:238]: ok

**Review by Wondertan — APPROVED** [review]

**Review by walldiss — APPROVED** [review]
