### PR TITLE
Fix `GetSharesByNamespace` ordering

### LINKED ISSUE #621: `GetSharesByNamespace` returns shares in non-deteministic order
[`GetSharessByNamespace`](https://github.com/celestiaorg/celestia-node/blob/28020da54d46b2dec29763a51c6c434b157e84dd/service/share/share.go#L153) spawns a goroutine for each `roodCID`, and results are returned via channel, and appended to an array:
https://github.com/celestiaorg/celestia-node/blob/28020da54d46b2dec29763a51c6c434b157e84dd/service/share/share.go#L188

Because of this, the order of returned shares is non-deterministic.

### PR DESCRIPTION
**Pull request by tzdybal**
Resolves #621.

### CODE REVIEW

File: service/share/share.go [hunk 1]
```diff
@@ -161,37 +161,37 @@ func (s *service) GetSharesByNamespace(ctx context.Context, root *Root, nID name
...
+		case err := <-errCh:
+			if err != nil {
+				return nil, err
 			}
 		case <-ctx.Done():
 			return nil, ctx.Err()
 		}
 	}
 
+	namespacedShares := make([]Share, 0)
```
Comment (Wondertan) [inline service/share/share.go:188]: Preallocate capacity pls

File: service/share/share.go [hunk 2]
```diff
@@ -161,37 +161,37 @@ func (s *service) GetSharesByNamespace(ctx context.Context, root *Root, nID name
...
-			resultCh <- &res{nodes: nodes, err: err}
-		}(rootCID)
+	errCh := make(chan error)
+	nodes := make([][]format.Node, len(rowRootCIDs))
+	for i, rootCID := range rowRootCIDs {
+		go func(i int, rootCID cid.Cid) {
+			var err error
+			nodes[i], err = ipld.GetLeavesByNamespace(ctx, s.dag, rootCID, nID)
+			errCh <- err
+		}(i, rootCID)
```
Comment (Wondertan) [inline service/share/share.go:174]: Nice!

File: service/share/share.go [hunk 3]
```diff
@@ -161,37 +161,37 @@ func (s *service) GetSharesByNamespace(ctx context.Context, root *Root, nID name
...
 		select {
-		case result := <-resultCh:
-			if result.err != nil {
-				return nil, result.err
-			}
-			for _, node := range result.nodes {
-				namespacedShares = append(namespacedShares, node.RawData()[1:])
+		case err := <-errCh:
+			if err != nil {
+				return nil, err
```
Comment (Wondertan) [inline service/share/share.go:181]: nit: In this case now, it would be nicer/cleaner to use [errgoup](https://pkg.go.dev/golang.org/x/sync/errgroup) instead, but not necessary.

**Review by Wondertan — COMMENTED** [review]
Thank you for the quick fix. And a special thank you for propper commit format!

Left two nits, otherwise LGTM

File: service/share/share.go (hunk 1 above)
Comment (tzdybal) [reply service/share/share.go:188]: Each node can have arbitrary number of shares inside. So without iterating, can't per-allocate _precisely_. Another option is to push number of shares along with the error using a channel. Both adds complexity.
I can also pre-allocate for `len(nodes)` aka `len(rowRootCIDs)`.

File: service/share/share.go (hunk 3 above)
Comment (tzdybal) [reply service/share/share.go:181]: Oh, I didn't know you use errgroup in node :) Will fix.

File: service/share/share.go (hunk 1 above)
Comment (Wondertan) [reply service/share/share.go:188]: Oh, true, we never know precisely how many shares we submit unless we encode the number of shares in the first metadata like share when PFD is sent. 

It is fine for now to keep it as it is then.

**Review by Wondertan — APPROVED** [review]
👍

**Review by renaynay — APPROVED** [review]
Thanks for finding + fixing :)

**Review by liamsi — APPROVED** [review]

File: service/share/share.go [hunk 4]
```diff
@@ -161,34 +163,25 @@ func (s *service) GetSharesByNamespace(ctx context.Context, root *Root, nID name
...
-		select {
-		case result := <-resultCh:
-			if result.err != nil {
-				return nil, result.err
-			}
-			for _, node := range result.nodes {
-				namespacedShares = append(namespacedShares, node.RawData()[1:])
-			}
-		case <-ctx.Done():
-			return nil, ctx.Err()
```
Comment (liamsi) [inline service/share/share.go:191]: Q: Wouldn't this have been fixable by sorting the returned shares before returning them?
