### PR TITLE
Fix start order of mocknet

### LINKED ISSUE #173: tests: `TestSubscriber` can hang / sometimes fails due to `context deadline exceeded`
## Proof
image

## Refs
Found in #171 

## Possible solution
There has to be a small 200 milliseconds timeout after the first Subscription on PubSub Topic. Basically, we need to ensure that peers notified each other about joining a topic before they are sending the msg. Otherwise, msg will never find a recipient.

### PR DESCRIPTION
**Pull request by atoulme**
Fixes #173 by separating the creation of the hosts from connecting them, allowing that we configure the gossip protocol on them, otherwise the host doesn't know to gossip with the other host.

### CODE REVIEW

File: service/header/subscription_test.go [hunk 1]
```diff
@@ -54,9 +51,16 @@ func TestSubscriber(t *testing.T) {
 	err = p2pSub2.Start(context.Background())
 	require.NoError(t, err)
 
+	err = net.ConnectAllButSelf()
+	time.Sleep(400 * time.Millisecond) // wait for peers to finish their connection.
```
Comment (renaynay) [inline service/header/subscription_test.go:55]: Is this necessary even though we wait for the method to return?

Comment (renaynay) [inline service/header/subscription_test.go:55]:
```suggestion
        require.NoError(t, err)
	time.Sleep(400 * time.Millisecond) // wait for peers to finish their connection.
```

**Review by renaynay — COMMENTED** [review]
LFG @atoulme 🚀

File: service/header/subscription_test.go (hunk 1 above)
Comment (liamsi) [reply service/header/subscription_test.go:55]: If it is necessary, is there a way to learn about peers finishing up their conns reliably independent of a sleep? If not, then maybe even increase those milliseconds as this might fail on time to time if there is load on the github servers.

File: service/header/subscription_test.go [hunk 2]
```diff
@@ -36,9 +36,6 @@ func TestSubscriber(t *testing.T) {
 	err = p2pSub1.Start(context.Background())
 	require.NoError(t, err)
 
-	// subscribe
-	subscription, err := p2pSub1.Subscribe()
-	require.NoError(t, err)
```
Comment (liamsi) [inline service/header/subscription_test.go:39]: Remove one newline to please the linter (or run `gofmt -s` on the file):
```
service/header/subscription_test.go#L39
File is not `gofmt`-ed with `-s` (gofmt)
```

**Review by liamsi — COMMENTED** [review]
Thanks for this @atoulme 🙏🏼 

Looks good! Let's merge this after 
- https://github.com/celestiaorg/celestia-node/pull/342#discussion_r782915222 and 
- https://github.com/celestiaorg/celestia-node/pull/342#discussion_r782932001
are addressed.

**Review by Wondertan — CHANGES_REQUESTED** [review]
Hey @atoulme. Thank you for PR! This is our long-living and annoying issue with PubSub testing and it is hard to fix this. Unfortunately, this fix does not fix the issue entirely. We were actively using sleep here sometime before and it does not guarantee test success. GH CI can be overloaded so that even a second of sleep didn't help. The proper solution would be to follow what [go-legs](https://github.com/filecoin-project/go-legs/blob/main/test/util.go#L33) is doing.

File: service/header/subscription_test.go (hunk 1 above)
Comment (Wondertan) [reply service/header/subscription_test.go:55]: We had sleeps before. They do not fix the issue unless the sleep is ridiculously big.

Comment (atoulme) [reply service/header/subscription_test.go]: Good catch thanks :)

Comment (atoulme) [reply service/header/subscription_test.go]: I have removed the need for a sleep by watching the peer store of both peers, and making sure that both have connected. I run the check against a timeout of 2 seconds to acknowledge the wonkiness of github actions.

I have run the test in a loop 1000 times to make sure it was a good fix, and it held well.

File: service/header/subscription_test.go [hunk 3]
```diff
@@ -18,7 +18,7 @@ func TestSubscriber(t *testing.T) {
 	defer cancel()
 
 	// create mock network
-	net, err := mocknet.FullMeshConnected(ctx, 2)
```
[the remark this answers is not in the document]
Comment (atoulme) [reply service/header/subscription_test.go:21]: The problem here is that there are transient states where the peers are connected, but they don't have both the protocols set. So they would not know for example to talk over gossip. By turning debug logging on, I found for example that the peer connection emitted an error: `error opening stream protocol not supported`.

By digging a bit, I found that one node was connecting with the pubsub protocols, while the other had just started and didn't have protocols set.
So the first fix was to start both p2psubcribers then get them to connect.

The second problem was to acknowledge that nodes were actually in a race condition to connect. I had missed that mocknet was not only registering the nodes, but also connecting them right away, before setting protocols. Hat tip to Rene for pointing that mocknet was maybe the problem.
So the second fix consisted in separating creating the mocknet, and then starting the peer connections after protocols are set so we eliminate this race condition.

Finally, I still had issues, hence the `time.Sleep(400 * time.Millisecond)` which I just refactored into a check, to make sure peers were well connected.
That third scenario came from the fact that `Subscribe` could execute faster than the peer connection. The `Subscribe` call sends a RPC message to the peer requesting subscribing to a topic. The node will loop over its peers to find ones that have the same gossip topics. As the peers are not connected yet, the node will find no peers matching the gossip topic, and drop the message. That's what the code at https://github.com/libp2p/go-libp2p-pubsub/blob/7ef0669764b94ed11e8b5b0128ee408942ebe5eb/pubsub.go#L860 makes me believe.
To fix that third bug, I made sure to wait that peers are correctly both connected to subscribe.

Hopefully, this rationale makes sense. After all those changes, I ran the test in a loop for 1000 occurrences without issues. I didn't check how go-legs fixes this issue, I hope those changes are useful. Cheers!

File: service/header/subscription_test.go (hunk 2 above)
Comment (atoulme) [reply service/header/subscription_test.go]: No problem. Fixed.

File: service/header/subscription_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (Wondertan) [reply service/header/subscription_test.go:21]: Ok, so the transient state you are talking about is when IdentifyProtocol yet didn't finish a handshake. Makes sense about it causing the problems.

File: service/header/subscription_test.go [hunk 4]
```diff
@@ -54,9 +50,33 @@ func TestSubscriber(t *testing.T) {
 	err = p2pSub2.Start(context.Background())
 	require.NoError(t, err)
 
+	done := make(chan bool, 1)
+	go func() {
+		for {
+			if net.Hosts()[1].Peerstore().Peers().Len() == 2 && net.Hosts()[0].Peerstore().Peers().Len() == 2 {
+				close(done)
+				break
```
Comment (Wondertan) [inline service/header/subscription_test.go:58]: Return?

File: service/header/subscription_test.go [hunk 5]
```diff
@@ -54,9 +50,33 @@ func TestSubscriber(t *testing.T) {
...
+			}
+			time.Sleep(100 * time.Millisecond)
+		}
+	}()
+	ticker := time.NewTicker(2 * time.Second)
```
Comment (Wondertan) [inline service/header/subscription_test.go:63]: Do we need to tick periodcally? time.Timer ?

File: service/header/subscription_test.go [hunk 6]
```diff
@@ -54,9 +50,33 @@ func TestSubscriber(t *testing.T) {
...
+	err = net.ConnectAllButSelf()
+	require.NoError(t, err)
+
+	select {
+	case <-done:
+	case <-ticker.C:
```
Comment (Wondertan) [inline service/header/subscription_test.go:69]: One more even preferred option would be to rely on the global timeout set in the context by using <-ctx.Done()

File: service/header/subscription_test.go [hunk 7]
```diff
@@ -54,9 +50,33 @@ func TestSubscriber(t *testing.T) {
 	err = p2pSub2.Start(context.Background())
 	require.NoError(t, err)
 
+	done := make(chan bool, 1)
+	go func() {
+		for {
+			if net.Hosts()[1].Peerstore().Peers().Len() == 2 && net.Hosts()[0].Peerstore().Peers().Len() == 2 {
```
Comment (Wondertan) [inline service/header/subscription_test.go:56]: We can make this even better by using Host's EventBus and waiting for `event.EvtPeerIdentificationCompleted`. Would be cool if you can implement this instead to remove sleeps and this loop entirely.

**Review by Wondertan — COMMENTED** [review]
Thank for the detailed rationale. Pls consider suggestions

File: service/header/subscription_test.go (hunk 7 above)
Comment (liamsi) [reply service/header/subscription_test.go:56]: That is a good idea. I think we should open an issue and use this approach where feasible in general (I'm sure there are more places where this could be applied). Might be reasonable to do this in a followup PR later.

File: service/header/subscription_test.go (hunk 5 above)
Comment (atoulme) [reply service/header/subscription_test.go:63]: D'oh

File: service/header/subscription_test.go (hunk 6 above)
Comment (atoulme) [reply service/header/subscription_test.go:69]: neat, will use that

File: service/header/subscription_test.go [hunk 8]
```diff
@@ -54,9 +50,33 @@ func TestSubscriber(t *testing.T) {
...
+		}
+	}()
+	ticker := time.NewTicker(2 * time.Second)
+	err = net.ConnectAllButSelf()
+	require.NoError(t, err)
+
+	select {
+	case <-done:
+	case <-ticker.C:
+		assert.Fail(t, "timeout waiting for peers to connect")
```
[the remark this answers is not in the document]
Comment (atoulme) [reply service/header/subscription_test.go:70]: good point

File: service/header/subscription_test.go (hunk 4 above)
Comment (atoulme) [reply service/header/subscription_test.go:58]: ok sure

File: service/header/subscription_test.go (hunk 7 above)
Comment (atoulme) [reply service/header/subscription_test.go]: added it, seems to work nicely.

**Review by renaynay — DISMISSED** [review]
LGTM - thanks for all your work @atoulme and your suggestions @Wondertan !

File: service/header/subscription_test.go [hunk 9]
```diff
@@ -54,9 +51,44 @@ func TestSubscriber(t *testing.T) {
...
+			case <-sub0.Out():
+				foundSub0 = true
+			case <-sub1.Out():
+				foundSub1 = true
+			}
+			if foundSub0 && foundSub1 {
+				close(done)
+				return
+			}
+		}
```
[the remark this answers is not in the document]
Comment (Wondertan) [reply service/header/subscription_test.go:74]: It is ok two rely on `2` here as we already access net.Hosts()[0] knowing how many hosts we have.

File: service/header/subscription_test.go [hunk 10]
```diff
@@ -54,9 +51,44 @@ func TestSubscriber(t *testing.T) {
...
+	}()
+	err = net.ConnectAllButSelf()
+	require.NoError(t, err)
+
+	select {
+	case <-done:
+	case <-ctx.Done():
+		assert.FailNow(t, "timeout waiting for peers to connect")
+	}
```
Comment (Wondertan) [inline service/header/subscription_test.go:83]: It is not necessary to wait for events in a separate routine and then wait on custom done chan here. Instead, we can simplify this by blocking on event subscriptions here directly with the same looping twice tip above. So in the end we can eliminate:
* goroutine
* bools 
* select 
* done chan

**Review by Wondertan — COMMENTED** [review]
One more review round, mostly to simplify code

**Review by renaynay — APPROVED** [review]

**Review by Wondertan — APPROVED** [review]
