### PR TITLE
fix(state): JSON marshaling for sdk Address wrapper

### LINKED ISSUE #2322: "unmarshaling params for 'state.BalanceForAddress' (param: *types.Address): json: cannot unmarshal string into Go value of type types.Address"
### Celestia Node version

v0.11.0-rc2

### OS

macOS

### Install tools

https://docs.celestia.org/nodes/celestia-node/ for Mac (Apple) x Arabica

### Others

_No response_

### Steps to reproduce it

```bash
celestia rpc state BalanceForAddress celestia10rtd9lhel2cuh6c659l25yncl6atcyt37umard
```

### Expected result

balance of address

### Actual result

`message": "unmarshaling params for 'state.BalanceForAddress' (param: *types.Address): json: cannot unmarshal string into Go value of type types.Address"`

### Relevant log output

```Shell
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32700,
    "message": "unmarshaling params for 'state.BalanceForAddress' (param: *types.Address): json: cannot unmarshal string into Go value of type types.Address"
  }
}
```

### Notes

_No response_

### PR DESCRIPTION
**Pull request by distractedm1nd**
While debugging #2322 , I noticed that it is not only an RPC issue, but also a broken API one. All RPC methods that used the type `state.Address` were unusable, both via the client and via raw JSON calls. This is because the server was unable to marshal the address string value back into the interface type. 

To circumvent this, I have embedded the sdk.Address type in the same way that we embed the fraud proof type, to allow us to unmarshal it back into a concrete type. I have also added unit tests to fix this.

In addition, it fixes the RPC parsing - so it closes #2322 .

### CODE REVIEW

File: state/state.go [hunk 1]
```diff
@@ -15,8 +18,11 @@ type Tx = coretypes.Tx
 // TxResponse is an alias to the TxResponse type from Cosmos-SDK.
 type TxResponse = sdk.TxResponse
 
-// Address is an alias to the Address type from Cosmos-SDK.
-type Address = sdk.Address
+// Address is an alias to the Address type from Cosmos-SDK. It is embedded into a struct to provide
```
Comment (Wondertan) [inline state/state.go:21]: Its technically not an alias anymore

Comment (Wondertan) [reply state/state.go:21]: Also, why not 'type Address sdk.Address'? Without =

Comment (Wondertan) [reply state/state.go:21]: Ah, because address is an interface?

**Review by Wondertan — COMMENTED** [review]
So the core issue here is that cosmos sdk addresses does not implement json serialisation and reflection does not work automatically, right?

File: state/state.go (hunk 1 above)
Comment (distractedm1nd) [reply state/state.go:21]: Reflection cannot work on interface types like that, because you never know which concrete type to marshal a value back into. I need to double check that no other api endpoints are returning interfaces - because it breaks the server

File: state/state.go [hunk 2]
```diff
@@ -26,3 +32,27 @@ type AccAddress = sdk.AccAddress
...
+	addr, err := sdk.AccAddressFromBech32(addrString)
+	if err != nil {
+		// first check if it is a validator address and can be converted
+		valAddr, err := sdk.ValAddressFromBech32(addrString)
+		if err != nil {
+			return fmt.Errorf("address must be a valid account or validator address: %w", err)
+		}
+		a.Address = valAddr
+		return nil
+	}
```
Comment (Wondertan) [inline state/state.go:49]: I feel like we have similar code somewhere.

File: state/state.go [hunk 3]
```diff
@@ -26,3 +32,27 @@ type AccAddress = sdk.AccAddress
 
 // Int is an alias to the Int type from Cosmos-SDK.
 type Int = math.Int
+
+func (a *Address) UnmarshalJSON(data []byte) error {
```
Comment (Wondertan) [inline state/state.go:36]: Any reason to keep this as method on ptr, while Marshal is method on val?

File: state/address_test.go [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+	testCases := []struct {
+		name           string
+		addressString  string
+		addressFromStr func(string) (interface{}, error)
+		marshalJSON    func(interface{}) ([]byte, error)
+		unmarshalJSON  func([]byte) (interface{}, error)
+	}{
+		{
+			name:           "Account Address",
+			addressString:  "celestia1377k5an3f94v6wyaceu0cf4nq6gk2jtpc46g7h",
```
Comment (Wondertan) [inline state/address_test.go:21]: Leet address I would say

**Review by Wondertan — APPROVED** [review]
Thanks the tests!

File: state/state.go (hunk 2 above)
Comment (distractedm1nd) [reply state/state.go:49]: We do, in the gateway address parsing - but I have kept it there for better error handling

File: state/state.go [hunk 5]
```diff
@@ -26,3 +32,27 @@ type AccAddress = sdk.AccAddress
...
+		}
+		a.Address = valAddr
+		return nil
+	}
+
+	a.Address = addr
+	return nil
+}
+
+func (a Address) MarshalJSON() ([]byte, error) {
```
[the remark this answers is not in the document]
Comment (distractedm1nd) [reply state/state.go:55]: Yes, it is the json marshaling interface - and it actually is json encoding/decoding. The encoded value is a valid json value, which is a string (which explains the addition of the quotation marks to become a valid json value)

File: state/state.go (hunk 3 above)
Comment (distractedm1nd) [reply state/state.go:36]: Will test without

Comment (distractedm1nd) [reply state/state.go:36]: @Wondertan it panics without the pointer val. The marshal having a value receiver has to do with BalanceForAddress returning the value instead of the pointer, but it works on both pointers and values. 

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x104356c4c]

goroutine 1 [running]:
encoding/json.(*encodeState).marshal.func1()
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/encode.go:326 +0x80
panic({0x1053af8a0, 0x106d1efc0})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/runtime/panic.go:884 +0x204
github.com/celestiaorg/celestia-node/state.Address.MarshalJSON(...)
	/Users/rford/Programming/Celestia/celestia-node/state/state.go:57
encoding/json.marshalerEncoder(0x14000187c80, {0x105628700?, 0x14001912df0?, 0x105764fe0?}, {0x0?, 0x87?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/encode.go:477 +0xb8
encoding/json.condAddrEncoder.encode({0x10579c480?, 0x10579c4d0?}, 0x140018e1528?, {0x105628700?, 0x14001912df0?, 0x105628700?}, {0x38?, 0x15?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/encode.go:960 +0x78
encoding/json.(*encodeState).reflectValue(0x105340ce0?, {0x105628700?, 0x14001912df0?, 0x102b37198?}, {0xd8?, 0x15?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/encode.go:358 +0x70
encoding/json.interfaceEncoder(0x14000187c80, {0x105340ce0?, 0x14001912de0?, 0x102907618?}, {0xa5?, 0xfd?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/encode.go:714 +0xcc
encoding/json.arrayEncoder.encode({0x140018e1708?}, 0x14000187c80, {0x10527e020?, 0x14000018c28?, 0x80?}, {0xe0?, 0xed?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/encode.go:914 +0xc0
encoding/json.sliceEncoder.encode({0x140018e17e8?}, 0x14000187c80, {0x10527e020?, 0x14000018c28?, 0x6?}, {0x9?, 0x0?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/encode.go:887 +0x260
encoding/json.structEncoder.encode({{{0x14001618fc0?, 0x1057fc360?, 0x1400136c030?}, 0x140011d23c0?}}, 0x14000187c80, {0x1055a1740?, 0x14000018c00?, 0x1055a1740?}, {0x30?, 0x23?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/encode.go:759 +0x178
encoding/json.(*encodeState).reflectValue(0x14000187c80?, {0x1055a1740?, 0x14000018c00?, 0x102b33298?}, {0x78?, 0x0?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/encode.go:358 +0x70
encoding/json.(*encodeState).marshal(0x140018e1a58?, {0x1055a1740?, 0x14000018c00?}, {0x40?, 0x0?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/encode.go:330 +0x120
encoding/json.Marshal({0x1055a1740, 0x14000018c00})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/encode.go:161 +0x94
main.sendJSONRPCRequest({0x16d5073ed?, 0x11?}, {0x16d5073f3, 0x11}, {0x14001912de0, 0x1, 0x1})
	/Users/rford/Programming/Celestia/celestia-node/cmd/celestia/rpc.go:337 +0x118
main.glob..func5(0x106d401a0?, {0x14000018b80?, 0x4?, 0x4?})
	/Users/rford/Programming/Celestia/celestia-node/cmd/celestia/rpc.go:99 +0x90
github.com/spf13/cobra.(*Command).execute(0x106d401a0, {0x14000018b00, 0x4, 0x4})
	/Users/rford/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x106d3fec0)
	/Users/rford/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/rford/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/rford/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
main.run()
	/Users/rford/Programming/Celestia/celestia-node/cmd/celestia/main.go:28 +0x64
main.main()
	/Users/rford/Programming/Celestia/celestia-node/cmd/celestia/main.go:21 +0x1c
```

Comment (Wondertan) [reply state/state.go:36]: My point is mostly why this is asymmetric. I am fine with either, as long as it symmetric

Comment (distractedm1nd) [reply state/state.go:36]: No, it cannot be symmetric - thats my point. The receiver needs to be a value type on the unmarshal

File: state/state.go [hunk 6]
```diff
@@ -26,3 +32,27 @@ type AccAddress = sdk.AccAddress
...
+	addrString := strings.Trim(string(data), "\"")
+	addr, err := sdk.AccAddressFromBech32(addrString)
+	if err != nil {
+		// first check if it is a validator address and can be converted
+		valAddr, err := sdk.ValAddressFromBech32(addrString)
+		if err != nil {
+			return fmt.Errorf("address must be a valid account or validator address: %w", err)
+		}
+		a.Address = valAddr
+		return nil
```
Comment (renaynay) [inline state/state.go:48]: nit: I'd un-nest this logic

**Review by renaynay — APPROVED** [review]

File: cmd/celestia/rpc.go [hunk 7]
```diff
@@ -392,18 +390,12 @@ func sendJSONRPCRequest(namespace, method string, params []interface{}) {
...
-		valAddr, err := types.ValAddressFromBech32(addrStr)
-		if err != nil {
-			return nil, errors.New("address must be a valid account or validator address ")
-		}
-		return valAddr, nil
+		return address, err
 	}
-
-	return addr, nil
+	return address, nil
```
[the remark this answers is not in the document]
Comment (distractedm1nd) [reply cmd/celestia/rpc.go:398]: I prefer returning explicit nil
