### PR TITLE
fix(ipld/plugin): verify that data written to namespaceHasher has legit size

### LINKED ISSUE #780: Light Node panics
I was running my Light Node as always, while suddenly I saw a panic. Currently have no idea what can be an issue.
image

### LINKED ISSUE #952: Crash during syncing full storage node
### Celestia Node version

v0.3.0-rc2

### OS

Ubuntu 20.04.4

### Install tools

I used screen. At 1 working validator node well. At 2 im trying to sync full storge node. I think it has no effect.

### Others

_No response_

### Steps to reproduce it

celestia full start --core.grpc https://celestia-testnet-rpc.polkachu.com/:9090 --keyring.accname Vanish   (at other RPC Endpoints it killing process after aroung 3k blocks)

### Expected result

full sync)

### Actual result

unknown

### Relevant log output

```shell
goroutine 431031371 [running]:

github. com/celestiaorg/nmt. (*Hasher) .HashNode (0xc05590d530, {0xc09ba8c3cl, 0x30, Ox3f}, {OxcO9ba8c3f1, 0x6, Oxf}) /root/go/pkg/mod/github.com/celestiaorg/nmt@v0.10.0/hasher.go:122 +0x545
github. com/celestiaorg/celestia-node/ipld/plugin. (*namespaceHasher) .Sum(0xc05590d560, {0xc000118b10, 0x7701, Oxc0bc2a2b98}) /root/celestia-node/ipld/plugin/nmt.go:69 +0x8f
github. com/multiformats/go-multihash.encodeHash ({0x2c48838, 0xc05590d560}, 0x7701, 0x30) 
/root/go/pkg/mod/ github. com/multiformats/go-multihash@v0.2.0/sum.go:54 +0x42

github. com/multiformats/go-multihash.Sum{{0xc09ba8c3c0, 0x37, 0x40}, Ox1?, 0x7701?)
/root/go/pkg/mod/ github. com/multiformats/go-multihash@v0.2.0/sum.go:30 +0x90
github.com/ipfs/go-cid. Prefix.Sum({{0xc0al70f£018?, 0x8?, 0x8?, 0xc0263e2900?7}, {Oxc09ba8c3c0?, Oxc0bc2a2c80?, 0x4850257}) /root/go/pkg/mod/github.com/ipfs/go-cid@v0.2.0/cid.go:532 +0xa5S
github. com/ipfs/go-bitswap/message.newMessageFromProto({{{0x0, 0x0, 0x0}, Ox0}, {0x0, 0x0, 0x0}, {0xc0263e2900, 0x2, 0x2}, ...}) /root/go/pkg/mod/github.com/ipfs/go-bitswap@v0.7.0/message/message.go:222 +0xlbb
github. com/ipfs/go-bitswap/message. FromMsgReader ({0x7£45908857d8, 0xc02a282480}) /root/go/pkg/mod/github.com/ipfs/go-bitswap@v0.7.0/message/message.go:416 +0x118
github. com/ipfs/go-bitswap/network. (*impl) .handleNewStream(0xc0012bcd20, {0x2c57888?, Oxc05cb8c200})
/root/go/pkg/mod/github.com/ipfs/go-bitswap@v0.7.0/network/ipfs_impl.go:413 +0x39c 
github. com/libp2p/go-libp2p/p2p/host/basic. (*BasicHost) .SetStreamHandler.funcl {{0xc014b2£350, 0x23}, {0x7£4590bb6e98?, Oxc05cb8c200}) /root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.20.2/p2p/host/basic/basic_host.go:568 +0x76
created by github.com/libp2p/go-libp2p/p2p/host/basic. (*BasicHost) .newStreamHandler /root/go/pkg/mod/github . com/1ibp2p/go-1ibp2pev0 . 20. 2/p2p/host/basic/basic_host.go:411 +0x715
```

### Notes

_No response_

### PR DESCRIPTION
**Pull request by Wondertan**
My understanding of the bug right now is that the bitswap msg that was rcvd from the network had the wrong size of inner nodes hashes, and instead of erroring out, our IPLD plugin panics. It's not clear what could cause the wrong msg size under normal conditions, but it's clear that we have to fix it by checking if the sizes of msgs are correct.

Closes #952 and closes #780

### CODE REVIEW

**Review by renaynay — COMMENTED** [review]
Can you make a quick unit test for this?

File: ipld/plugin/nmt.go [hunk 1]
```diff
@@ -53,9 +53,24 @@ func NewNamespaceHasher(hasher *nmt.Hasher) hash.Hash {
...
+	case (nln*2+hln)*2 + 1: // with type byte
+		fallthrough
+	case (nln*2 + hln) * 2:
+		n.tp = nmt.NodePrefix
+	// leaf data node
+	case hln + 256:
+		fallthrough
+	case hln + 256 + 1: // with type byte
+		n.tp = nmt.LeafPrefix
+	}
```
Comment (Wondertan) [inline ipld/plugin/nmt.go:70]: Note that there 4 cases, as I made this code in preparation for type byte removal. Having 4 cases here would allow us to remove the type byte + ensure that existing data on the network continues to work

**Comment by Wondertan** [comment]
@renaynay, I can make a test that would just test the hasher itself, but FWIW it does not bring any value. To actually test this, we need somehow simulate that over bitswap we rcv a wrong size msg, which is a big PITA

**Comment by Wondertan** [comment]
Tests were failing due to a typo. Fixed now

**Review by adlerjohn — COMMENTED** [review]
Can you file an issue to add such a test so we don't forget at least?

File: ipld/plugin/nmt.go [hunk 2]
```diff
@@ -53,9 +53,24 @@ func NewNamespaceHasher(hasher *nmt.Hasher) hash.Hash {
...
+	switch ln {
+	default:
+		return 0, fmt.Errorf("wrong data size")
+	// inner node
+	case (nln*2+hln)*2 + 1: // with type byte
+		fallthrough
+	case (nln*2 + hln) * 2:
+		n.tp = nmt.NodePrefix
+	// leaf data node
+	case nln + 256:
```
Comment (liamsi) [inline ipld/plugin/nmt.go:66]: Please use the constant from core instead of `256`. Also, note that we will change to 512 byte shares soon: https://github.com/celestiaorg/celestia-core/issues/724

**Review by liamsi — CHANGES_REQUESTED** [review]

File: ipld/plugin/nmt.go [hunk 3]
```diff
@@ -53,9 +53,24 @@ func NewNamespaceHasher(hasher *nmt.Hasher) hash.Hash {
...
+		fallthrough
+	case nln + 256 + 1: // with type byte
```
Comment (liamsi) [inline ipld/plugin/nmt.go:68]: Or, at least use a constant.

File: ipld/plugin/nmt.go (hunk 2 above)
Comment (Wondertan) [reply ipld/plugin/nmt.go:66]: Thanks for noting that, @liamsi.  I thought about that, but then the cycle dependency issue stopped me from doing that(ipld/plungin cannot import ipld)but this anyway has to be fixed in this PR. The dependency cycle will be resolved by #878, but before that I will just import directly from App.

File: ipld/plugin/nmt.go (hunk 3 above)
Comment (Wondertan) [reply ipld/plugin/nmt.go]: Done

File: ipld/plugin/nmt.go (hunk 2 above)
Comment (Wondertan) [reply ipld/plugin/nmt.go]: Done

**Comment by Wondertan** [comment]
An issue to test this out: https://github.com/celestiaorg/celestia-node/issues/981
If we think this is super-duper important, I can spend a day or two writing it. The day or two because it's not straightforward and it may require forking bitswap.

**Review by liamsi — APPROVED** [review]
lgtm

File: ipld/plugin/nmt.go [hunk 4]
```diff
@@ -53,9 +53,24 @@ func NewNamespaceHasher(hasher *nmt.Hasher) hash.Hash {
 }
 
 func (n *namespaceHasher) Write(data []byte) (int, error) {
-	n.tp = data[0]
+	ln, nln, hln := len(data), int(n.NamespaceLen), n.Hash.Size()
+	switch ln {
+	default:
+		return 0, fmt.Errorf("wrong data size")
+	// inner node
+	case (nln*2+hln)*2 + 1: // with type byte
```
[the remark this answers is not in the document]
Comment (Wondertan) [reply ipld/plugin/nmt.go:61]: Yes

[the remark this answers is not in the document]
Comment (Wondertan) [reply ipld/plugin/nmt.go]: Changed

File: ipld/plugin/nmt.go [hunk 5]
```diff
@@ -53,9 +53,25 @@ func NewNamespaceHasher(hasher *nmt.Hasher) hash.Hash {
...
+	case innerNodeSize + 1: // with type byte
+		fallthrough
+	case innerNodeSize:
+		n.tp = nmt.NodePrefix
+	// leaf data node
+	case leafNodeSize:
+		fallthrough
+	case leafNodeSize + 1: // with type byte
+		n.tp = nmt.LeafPrefix
+	}
```
Comment (renaynay) [inline ipld/plugin/nmt.go:71]:
```suggestion
	switch ln {
	default:
		return 0, fmt.Errorf("wrong data size")
	// inner node
	case innerNodeSize, innerNodeSize + 1: // with additional type byte
		n.tp = nmt.NodePrefix
	// leaf data node
	case leafNodeSize, leafNodeSize + 1: // with additional type byte
		n.tp = nmt.LeafPrefix
	}
```

**Review by renaynay — APPROVED** [review]
Last nit but is optional

File: ipld/plugin/nmt.go (hunk 5 above)
Comment (Wondertan) [reply ipld/plugin/nmt.go:71]: Nice
