### PR TITLE
fix(core): Do not propagate blocks if subscribed to blocks from incorrect chain

### LINKED ISSUE #3071: header/p2p: Mainnet nodes getting `mocha-4` headers
### Celestia Node version

12.1

### OS

ubuntu

### Install tools

_No response_

### Others

_No response_

### Steps to reproduce it

install and run light node like in the docs (defaults to mainnet without flags etc)

### Expected result

run on mainnet

### Actual result

2024-01-07T09:04:19.472-0800        ERROR        header/sync        sync/sync_head.go:175        invalid network header        {"height_of_invalid": 894619, "hash_of_invalid": "9E53A68FAC3C4051046A498E58C1C15E59CF306AAE8CC80D459A83EDF23E3BB4", "height_of_subjective": 503228, "hash_of_subjective": "8AD1E4F9C65A163312F344FDBDD17B71444D0EA42A12240F7401634AA45C6DD9", "reason": "wrong chain id: 'mocha-4' != 'celestia'"}

### Relevant log output

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by renaynay**
Right now, it is possible for a **bridge** node that was initialised and started on one chain (e.g. `mocha-4`) to be stopped and restarted on a different chain (e.g. `mainnet`) and propagate headers from the old chain (`mocha-4`) into the different network (`mainnet`). 

This PR fixes this issue by causing the listener to fatal if the listener recognises it is receiving blocks from a different chain to that which it expects.

Error will look like this: 

```
2024-01-10T16:06:22.001+0100	ERROR	core	core/listener.go:175	listener: received block with unexpected chain ID: expected arabica-11, received mocha-4
2024-01-10T16:06:22.001+0100	INFO	core	core/listener.go:177	listener: listening stopped
2024-01-10T16:06:22.001+0100	FATAL	core	core/listener.go:126	listener: invalid subscription
```

Resolves #3071

### CODE REVIEW

File: core/listener.go [hunk 1]
```diff
@@ -163,6 +171,12 @@ func (cl *Listener) listen(ctx context.Context, sub <-chan types.EventDataSigned
 				return errors.New("underlying subscription was closed")
 			}
 
+			if cl.chainID != "" && b.Header.ChainID != cl.chainID {
```
Comment (renaynay) [inline core/listener.go:174]: optionally, we can enforce the chainID on the listener. I'm not too picky with this component's code bc it will be removed hopefully soon ❤️

**Review by vgonkivs — APPROVED** [review]

**Comment by vgonkivs** [comment]
```
2024-01-10T15:12:43.958Z	ERROR	core	core/listener.go:175	listener: received block with unexpected chain ID: expected private, received LM01Di
2024-01-10T15:12:43.958Z	FATAL	core	core/listener.go:126	listener: invalid subscription
```

**Review by distractedm1nd — APPROVED** [review]

**Comment by renaynay** [comment]
Nice example of how i don't check the swamp tests.

**Review by vgonkivs — APPROVED** [review]

**Review by ramin — APPROVED** [review]

File: core/option.go [hunk 2]
```diff
@@ -13,3 +17,9 @@ func WithMetrics() Option {
 		p.metrics = true
 	}
 }
+
+func WithChainID(id p2p.Network) Option {
+	return func(p *params) {
+		p.chainID = id.String()
+	}
+}
```
Comment (walldiss) [inline core/option.go:25]: I'm curious about why it's optional. Could you share more about the scenarios where disabling chain name validation might be beneficial?

Comment (renaynay) [reply core/option.go:25]: Mostly so I didn't have to break constructor - I made a comment somewhere that i made it optional but we can also require it, I do not mind. This component is very temporary and hopefully to be removed in future.

**Review by walldiss — APPROVED** [review]
