### PR TITLE
fix(share/p2p)!: share.ErrNamespaceNotFound and integration into shrex-nd

### LINKED ISSUE #2145: bug(shares/GetSharesByNamespace): missing response type `ErrNamespaceNotFound`
In the current implementation, the response from a shrex-nd server for "Hey, my EDS store doesn't have that EDS, so I can't give you the ND" and "Hey, that EDS is in my store, and the data you are looking for doesn't exist in it" are the same. This causes many issues in the stack, leading to a timeout for `GetSharesByNamespace` calls, even when the correct response has been found. This will clearly require a protocol breaking change.

This must also be fixed in CascadeGetter, which should recognize the difference between `ErrNotFound`, which moves onto the next getter, and `ErrNamespaceNotFound`, which should return the data and error.

This means IPLDGetter should also return a `share.ErrNamespaceNotFound` for the same reason.

### PR DESCRIPTION
**Pull request by distractedm1nd**
This PR replaces #2156 , as gh was not showing the diff properly. It closes #2145

### CODE REVIEW

File: share/p2p/shrexnd/server.go [hunk 1]
```diff
@@ -130,12 +130,15 @@ func (srv *Server) handleNamespacedData(ctx context.Context, stream network.Stre
 	}
 
 	shares, err := srv.getter.GetSharesByNamespace(ctx, dah, req.NamespaceId)
-	if errors.Is(err, share.ErrNotFound) {
+	switch {
+	case errors.Is(err, share.ErrNotFound):
 		logger.Warn("server: nd not found")
```
Comment (renaynay) [inline share/p2p/shrexnd/server.go:135]: this log should be more relevant to the not found err

File: share/p2p/shrexnd/server.go [hunk 2]
```diff
@@ -130,12 +130,15 @@ func (srv *Server) handleNamespacedData(ctx context.Context, stream network.Stre
...
 		srv.respondNotFoundError(ctx, logger, stream)
 		return
-	}
-	if err != nil {
+	case errors.Is(err, share.ErrNamespaceNotFound):
```
Comment (renaynay) [inline share/p2p/shrexnd/server.go:138]: debug log here?

**Review by renaynay — APPROVED** [review]

File: share/p2p/shrexnd/server.go (hunk 2 above)
Comment (distractedm1nd) [reply share/p2p/shrexnd/server.go:138]: No need for a debug log. Its a successful case

**Review by walldiss — APPROVED** [review]
