### PR TITLE
fix(pruner): check nil context

### LINKED ISSUE #4543: bug(pruner): `onDelete` causes go-header to panic
Error: node: failed to start: error getting latest head during Start: subjective tail for head 8138303: moving tail from 8004805 to 8014206: deleting headers up to newly configured tail(8014206): header/store: delete to height 8014206: on delete handler for 8004805: header/store: user provided onDelete panicked on 8004805 with: runtime error: invalid memory address or nil pointer dereference

```
2025-09-11T11:55:15.787Z ERROR header/store store/store_delete.go:117 partial delete with error {"from_height": 8004805, "expected_to_height": 8014279, "actual_to_height": 8004805, "hdrs_not_found": 0, "took(s)": 0.000045947, "err": "on delete handler for 8004805: header/store: user provided onDelete panicked on 8004805 with: runtime error: invalid memory address or nil pointer dereference"}
```

ref: https://github.com/celestiaorg/go-header/issues/348

### PR DESCRIPTION
**Pull request by Wondertan**
Closes #4543 

This may happen when OnDelete is called before Pruner starts

### CODE REVIEW

File: pruner/service.go [hunk 1]
```diff
@@ -254,7 +254,7 @@ func (s *Service) retryFailed(ctx context.Context) {
 // * If Pruner prunes a header first - Syncer only removes the header
 //   - pruneOnHeaderDelete ignores the header based on updated checkpoint state
 func (s *Service) pruneOnHeaderDelete(ctx context.Context, height uint64) error {
-	if s.ctx.Err() != nil {
+	if s.ctx != nil && s.ctx.Err() != nil {
```
Comment (walldiss) [inline pruner/service.go:257]: Should it error on nil context?
```suggestion
	if s.ctx == nil || s.ctx.Err() != nil {
```
