### PR TITLE
fix(blob): add fixes along with the fuzzers that discovered them

### LINKED ISSUE #3727: blob: (*Blob).UnmarshalJSON crashes with simple JSON []byte("{}")
### Celestia Node version

1a1286f454c1dd670af856153a8fc8674cd91192

### OS

darwin

### Install tools

_No response_

### Others

_No response_

### Steps to reproduce it

If you run this very simple repro
```go
package test

import (
     "testing"

     "github.com/celestiaorg/celestia-node/blob"
)

func TestBlobUnmarshalRepro(t *testing.T) {
     blob := new(blob.Blob)
     _ = blob.UnmarshalJSON([]byte("{}"))
}
```

### Expected result

No panic

### Actual result

```shell
$ go test -run=Repro
# github.com/celestiaorg/celestia-node/blob.test
--- FAIL: TestBlobUnmarshalRepro (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 12 [running]:
testing.tRunner.func1.2({0x10e8315c0, 0xc000065740})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1635 +0x35e
panic({0x10e8315c0?, 0xc000065740?})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/runtime/panic.go:785 +0x132
github.com/celestiaorg/celestia-node/share.Namespace.Version(...)
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/share/namespace.go:61
github.com/celestiaorg/celestia-node/blob.(*Blob).UnmarshalJSON(0xc0005b1f20, {0xc0004e8a98, 0x2, 0x2})
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/blob.go:172 +0x1c5
github.com/celestiaorg/celestia-node/blob_test.TestBlobUnmarshalRepro(0xc0004116c0?)
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/repro_test.go:11 +0x4c
testing.tRunner(0xc0004116c0, 0x10e975e50)
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1743 +0x390
exit status 2
FAIL	github.com/celestiaorg/celestia-node/blob	1.501s
```

### Relevant log output

_No response_

### Is the node "stuck"? Has it stopped syncing?

_No response_

### Notes

To fix it, please check that the namespace is non-empty

```diff
diff --git a/blob/blob.go b/blob/blob.go
index 369d464e..3b26e5f1 100644
--- a/blob/blob.go
+++ b/blob/blob.go
@@ -168,6 +168,10 @@ func (b *Blob) UnmarshalJSON(data []byte) error {
 		return err
 	}
 
+	if len(jsonBlob.Namespace) == 0 {
+		return errors.New("expected a non-empty namespace")
+	}
+
 	b.Blob = &blob.Blob{}
 	b.Blob.NamespaceVersion = uint32(jsonBlob.Namespace.Version())
 	b.Blob.NamespaceId = jsonBlob.Namespace.ID()
```

### LINKED ISSUE #3728: blob: CommitmentProof.Verify should check and ensure that subtreeRootThreshold is >= 1 lest a divide-by-zero-panic
### Celestia Node version

1a1286f454c1dd670af856153a8fc8674cd91192

### OS

darwin

### Install tools

_No response_

### Others

_No response_

### Steps to reproduce it

While fuzzing the code for CommitmentProof.Verify, if I run this code

```go
package blob_test       

import (
        "testing"
        
        "github.com/celestiaorg/celestia-node/blob"
)       
                        
func TestCommitmentProofVerifyZeroSubThreshold(t *testing.T) {
        cp := new(blob.CommitmentProof)
        _, _ = cp.Verify(nil, 0)
}
```

we get a panic

### Expected result

No panic and instead an error

### Actual result

```shell
panic: runtime error: integer divide by zero
            goroutine 9589 [running]:
            runtime/debug.Stack()
            	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/runtime/debug/stack.go:26 +0x9b
            testing.tRunner.func1()
            	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1591 +0x1c8
            panic({0x106c66820?, 0x108121230?})
            	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/runtime/panic.go:785 +0x132
            github.com/celestiaorg/go-square/inclusion.SubTreeWidth(0xc0002596b7?, 0x1?)
            	/Users/emmanuelodeke/go/pkg/mod/github.com/celestiaorg/go-square@v1.1.0/inclusion/blob_share_commitment_rules.go:63 +0x212
            github.com/celestiaorg/celestia-node/blob.(*CommitmentProof).Verify(0xc00c545c20, {0x0, 0x0, 0x0}, 0x0)
            	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/commitment_proof.go:101 +0x25a
            github.com/celestiaorg/celestia-node/blob.FuzzCommitmentProofVerify.func1(0x0?, {0xc00112fb00, 0x17, 0xd80})
            	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/blob_fuzz_test.go:83 +0xfb
            reflect.Value.call({0x106bca9a0?, 0x106f64180?, 0x13?}, {0x1060d7eca, 0x4}, {0xc00d0580f0, 0x2, 0x2?})
            	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/reflect/value.go:581 +0xca6
            reflect.Value.Call({0x106bca9a0?, 0x106f64180?, 0x103a35ded?}, {0xc00d0580f0?, 0x106f5fe00?, 0xf?})
            	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/reflect/value.go:365 +0xb9
            testing.(*F).Fuzz.func1.1(0xc00d053ba0?)
            	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/fuzz.go:335 +0x305
            testing.tRunner(0xc00d053ba0, 0xc00d055320)
            	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1690 +0xf4
            created by testing.(*F).Fuzz.func1 in goroutine 22
            	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/fuzz.go:322 +0x577
```

## Suggested fix
```diff
diff --git a/blob/commitment_proof.go b/blob/commitment_proof.go
index 8fa74671..f9d1af06 100644
--- a/blob/commitment_proof.go
+++ b/blob/commitment_proof.go
@@ -2,6 +2,7 @@ package blob
 
 import (
 	"bytes"
+	"errors"
 	"fmt"
 
 	"github.com/celestiaorg/celestia-app/v2/pkg/appconsts"
@@ -93,6 +94,10 @@ func (commitmentProof *CommitmentProof) Verify(root []byte, subtreeRootThreshold
 		numberOfShares += proof.End() - proof.Start()
 	}
 
+	if subtreeRootThreshold <= 0 {
+		return false, errors.New("subtreeRootThreshould must be > 0")
+	}
+
 	// use the computed total number of shares to calculate the subtree roots
 	// width.
 	// the subtree roots width is defined in ADR-013:
```

/cc @liamsi @rootulp @musalbas

### LINKED ISSUE #3729: blob: VerifyCommitProof.Verify panics with "panic: runtime error: slice bounds out of range [:1] with capacity 0" for given simple repro
### Celestia Node version

1a1286f454c1dd670af856153a8fc8674cd91192

### OS

darwin

### Install tools

_No response_

### Others

_No response_

### Steps to reproduce it

```go
package blob_test

import (
        "testing"
        
        "github.com/celestiaorg/celestia-node/blob"
        "github.com/celestiaorg/nmt"
        "github.com/celestiaorg/nmt/pb"
)       
        
func TestCommitmentProofVerifySliceBound(t *testing.T) {
        proof := nmt.ProtoToProof(pb.Proof{End: 1})
        cp := &blob.CommitmentProof{
                SubtreeRootProofs: []*nmt.Proof{
                        &proof,
                },
        }
        _, _ = cp.Verify(nil, 1)
}
```

### Expected result

No panic, but just an error perhaps

### Actual result

```shell
--- FAIL: FuzzCommitmentProofVerify (0.02s)
    --- FAIL: FuzzCommitmentProofVerify/6a2b4b982dc67bf9 (0.00s)
panic: runtime error: slice bounds out of range [:1] with capacity 0 [recovered]
	panic: runtime error: slice bounds out of range [:1] with capacity 0

goroutine 13 [running]:
testing.tRunner.func1.2({0x107f22820, 0xc00054d950})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1635 +0x35e
panic({0x107f22820?, 0xc00054d950?})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/runtime/panic.go:785 +0x132
github.com/celestiaorg/celestia-node/blob.(*CommitmentProof).Verify(0xc0015897c0, {0x0, 0x0, 0x0}, 0x1)
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/commitment_proof.go:121 +0x73d
github.com/celestiaorg/celestia-node/blob.FuzzCommitmentProofVerify.func1(0x0?, {0xc00005d900, 0x4a, 0x50})
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/blob_fuzz_test.go:85 +0x172
reflect.Value.call({0x107ccd9a0?, 0x108067190?, 0x13?}, {0x107208138, 0x4}, {0xc001551e90, 0x2, 0x2?})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/reflect/value.go:581 +0xca6
reflect.Value.Call({0x107ccd9a0?, 0x108067190?, 0x105becfad?}, {0xc001551e90?, 0x108062e00?, 0xf?})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/reflect/value.go:365 +0xb9
testing.(*F).Fuzz.func1.1(0xc000655a00?)
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/fuzz.go:335 +0x305
testing.tRunner(0xc000655a00, 0xc00140cfc0)
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1690 +0xf4
created by testing.(*F).Fuzz.func1 in goroutine 12
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/fuzz.go:322 +0x577
exit status 2
FAIL	github.com/celestiaorg/celestia-node/blob	1.527s
```

## Suggested fix

```diff
diff --git a/blob/commitment_proof.go b/blob/commitment_proof.go
index 8fa74671..3975b528 100644
--- a/blob/commitment_proof.go
+++ b/blob/commitment_proof.go
@@ -108,6 +108,15 @@ func (commitmentProof *CommitmentProof) Verify(root []byte, subtreeRootThreshold
 		if err != nil {
 			return false, err
 		}
+
+		if len(commitmentProof.SubtreeRoots) < subtreeRootsCursor {
+			return false, fmt.Errorf("len(commitmentProof.SubtreeRoots)=%d < subtreeRootsCursor=%d",
+				len(commitmentProof.SubtreeRoots), subtreeRootsCursor)
+		}
+		if len(commitmentProof.SubtreeRoots) < subtreeRootsCursor+len(ranges) {
+			return false, fmt.Errorf("len(commitmentProof.SubtreeRoots)=%d < subtreeRootsCursor+len(ranges)=%d",
+				len(commitmentProof.SubtreeRoots), subtreeRootsCursor+len(ranges))
+		}
+
 		valid, err := subtreeRootProof.VerifySubtreeRootInclusion(
 			nmtHasher,
 			commitmentProof.SubtreeRoots[subtreeRootsCursor:subtreeRootsCursor+len(ranges)],
```

/cc @liamsi @rootulp @musalbas 

### Relevant log output

_No response_

### Is the node "stuck"? Has it stopped syncing?

_No response_

### Notes

_No response_

### LINKED ISSUE #3730: blob: CommitmentProof.Verify should firstly check that root is non-empty before doing all the validation work then crashing
### Celestia Node version

1a1286f454c1dd670af856153a8fc8674cd91192

### Steps to reproduce it

If we run this code repro
```go
package blob_test

import (
        "testing"

        "github.com/celestiaorg/celestia-app/v2/pkg/proof"
        "github.com/celestiaorg/celestia-node/blob" 
)       
        
func TestCommitmentProofRowProofVerify(t *testing.T) {
        cp := &blob.CommitmentProof{
                RowProof: proof.RowProof{
                        Proofs: []*proof.Proof{{}},
                },
        }       
        _, _ = cp.Verify(nil, 1)
}
```

### Expected result

An error and not a panic

### Actual result

```shell
$ go test -run=TestCommitmentProofRowProofVerify
# github.com/celestiaorg/celestia-node/blob.test
--- FAIL: TestCommitmentProofRowProofVerify (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 9 [running]:
testing.tRunner.func1.2({0x1069be820, 0xc000064c78})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1635 +0x35e
panic({0x1069be820?, 0xc000064c78?})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/runtime/panic.go:785 +0x132
github.com/celestiaorg/celestia-app/v2/pkg/proof.RowProof.VerifyProof({{0x0, 0x0, 0x0}, {0xc0010a7f58, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
	/Users/emmanuelodeke/go/pkg/mod/github.com/celestiaorg/celestia-app/v2@v2.1.2/pkg/proof/row_proof.go:32 +0x172
github.com/celestiaorg/celestia-node/blob.(*CommitmentProof).Verify(0xc0010a7eb8, {0x0, 0x0, 0x0}, 0x1)
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/commitment_proof.go:146 +0x779
github.com/celestiaorg/celestia-node/blob_test.TestCommitmentProofRowProofVerify(0xc000637860?)
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/repro_test.go:18 +0x94
testing.tRunner(0xc000637860, 0x106b030e0)
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1743 +0x390
exit status 2
FAIL	github.com/celestiaorg/celestia-node/blob	1.583s
```

### Relevant log output

```Shell
## Suggested fix

diff --git a/blob/commitment_proof.go b/blob/commitment_proof.go
index 8fa74671..f6af47a9 100644
--- a/blob/commitment_proof.go
+++ b/blob/commitment_proof.go
@@ -2,6 +2,7 @@ package blob
 
 import (
 	"bytes"
+	"errors"
 	"fmt"
 
 	"github.com/celestiaorg/celestia-app/v2/pkg/appconsts"
@@ -85,6 +86,10 @@ func (commitmentProof *CommitmentProof) Validate() error {
 // Expects the commitment proof to be properly formulated and validated
 // using the Validate() function.
 func (commitmentProof *CommitmentProof) Verify(root []byte, subtreeRootThreshold int) (bool, error) {
+	if len(root) == 0 {
+		return false, errors.New("root must be non-empty")
+	}
+
 	nmtHasher := nmt.NewNmtHasher(appconsts.NewBaseHashFunc(), share.NamespaceSize, true)
 
 	// computes the total number of shares proven.
@@ -93,6 +98,10 @@ func (commitmentProof *CommitmentProof) Verify(root []byte, subtreeRootThreshold
 		numberOfShares += proof.End() - proof.Start()
 	}
```

cc @liamsi @musalbas @rootulp

### LINKED ISSUE #3731: blob: CommitmentProof.Verify should firstly invoke .RowProof.Validate before invoking .RowProof.VerifyProof
### Celestia Node version

1a1286f454c1dd670af856153a8fc8674cd91192

### OS

darwin

```go
package blob_test 
                
import (                
        "testing"
        
        "github.com/celestiaorg/celestia-app/v2/pkg/proof"
        "github.com/celestiaorg/celestia-node/blob"
)       
        
func TestCommitmentProofRowProofVerifyWithEmptyRoot(t *testing.T) {
        cp := &blob.CommitmentProof{
                RowProof: proof.RowProof{
                        Proofs: []*proof.Proof{{}},
                },
        }
        root := []byte{0xd3, 0x4d, 0x34}
        _, _ = cp.Verify(root, 1)
} 
```

### Expected result

An error and no panic.

### Actual result

```shell
--- FAIL: TestCommitmentProofRowProofVerifyWithEmptyRoot (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 12 [running]:
testing.tRunner.func1.2({0x10e37e820, 0xc000901740})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1635 +0x35e
panic({0x10e37e820?, 0xc000901740?})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/runtime/panic.go:785 +0x132
github.com/celestiaorg/celestia-app/v2/pkg/proof.RowProof.VerifyProof({{0x0, 0x0, 0x0}, {0xc0006bcf58, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
	/Users/emmanuelodeke/go/pkg/mod/github.com/celestiaorg/celestia-app/v2@v2.1.2/pkg/proof/row_proof.go:32 +0x172
github.com/celestiaorg/celestia-node/blob.(*CommitmentProof).Verify(0xc0006bceb8, {0xc0006b0ab8, 0x3, 0x3}, 0x1)
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/commitment_proof.go:151 +0x850
github.com/celestiaorg/celestia-node/blob_test.TestCommitmentProofRowProofVerifyWithEmptyRoot(0xc0005c36c0?)
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/repro_test.go:19 +0xad
testing.tRunner(0xc0005c36c0, 0x10e4c30e8)
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1743 +0x390
exit status 2
FAIL	github.com/celestiaorg/celestia-node/blob	1.565s
```

## Suggested fix
Firstly ensure that we verify that there won't be an unexpected panic by the following

```diff
diff --git a/blob/commitment_proof.go b/blob/commitment_proof.go
index 8fa74671..82fed368 100644
--- a/blob/commitment_proof.go
+++ b/blob/commitment_proof.go
@@ -2,6 +2,7 @@ package blob
 
 import (
 	"bytes"
+	"errors"
 	"fmt"
 
 	"github.com/celestiaorg/celestia-app/v2/pkg/appconsts"
@@ -85,6 +86,15 @@ func (commitmentProof *CommitmentProof) Validate() error {
 // Expects the commitment proof to be properly formulated and validated
 // using the Validate() function.
 func (commitmentProof *CommitmentProof) Verify(root []byte, subtreeRootThreshold int) (bool, error) {
+	if len(root) == 0 {
+		return false, errors.New("root must be non-empty")
+	}
+
+	rp := commitmentProof.RowProof
+	if err := rp.Validate(root); err != nil {
+		return false, err
+	}
+
 	nmtHasher := nmt.NewNmtHasher(appconsts.NewBaseHashFunc(), share.NamespaceSize, true)
 
 	// computes the total number of shares proven.
@@ -93,6 +103,10 @@ func (commitmentProof *CommitmentProof) Verify(root []byte, subtreeRootThreshold
 		numberOfShares += proof.End() - proof.Start()
 	}
```

/cc @liamsi @musalbas @rootulp

### PR DESCRIPTION
**Pull request by odeke-em**
This changes adds fuzzers+corpra that found some bugs,
along with tests and reproducers to catch future regressions.

Fixes #3727
Fixes #3728
Fixes #3729
Fixes #3730
Fixes #3731

### CODE REVIEW

File: blob/repro_test.go [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+// Reported at https://github.com/celestiaorg/celestia-node/issues/3731.
+func TestCommitmentProofRowProofVerifyWithEmptyRoot(t *testing.T) {
+	cp := &blob.CommitmentProof{
+		RowProof: proof.RowProof{
+			Proofs: []*proof.Proof{{}},
+		},
+	}
+	root := []byte{0xd3, 0x4d, 0x34}
+	_, _ = cp.Verify(root, 1)
```
Comment (rach-id) [inline blob/repro_test.go:20]:
```suggestion
	_, err := cp.Verify(root, 1)
	assert.NoError(t, err)
```
maybe add an assertion in all of them to make sure we're receiving an error

**Review by rach-id — COMMENTED** [review]
nice catches 👍

File: blob/repro_test.go (hunk 1 above)
Comment (odeke-em) [reply blob/repro_test.go]: Initially it was to ensure no crashes but sure, I've added a check to ensure a non-nil error is returned for each.

**Review by Wondertan — APPROVED** [review]
:shipit:

File: blob/commitment_proof.go [hunk 2]
```diff
@@ -108,6 +122,15 @@ func (commitmentProof *CommitmentProof) Verify(root []byte, subtreeRootThreshold
 		if err != nil {
 			return false, err
 		}
+
+		if len(commitmentProof.SubtreeRoots) < subtreeRootsCursor {
+			return false, fmt.Errorf("len(commitmentProof.SubtreeRoots)=%d < subtreeRootsCursor=%d",
+				len(commitmentProof.SubtreeRoots), subtreeRootsCursor)
+		}
+		if len(commitmentProof.SubtreeRoots) < subtreeRootsCursor+len(ranges) {
```
Comment (cristaloleg) [inline blob/commitment_proof.go:130]: Do we need these 2 almost identical checks?

File: blob/repro_test.go [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+	"testing"
+
+	"github.com/celestiaorg/celestia-app/v2/pkg/proof"
+	"github.com/celestiaorg/celestia-node/blob"
+	"github.com/celestiaorg/nmt"
+	"github.com/celestiaorg/nmt/pb"
+)
+
+// Reported at https://github.com/celestiaorg/celestia-node/issues/3731.
+func TestCommitmentProofRowProofVerifyWithEmptyRoot(t *testing.T) {
```
Comment (cristaloleg) [inline blob/repro_test.go:13]: Why not aggregate all this test as sub-tests? Example:

```
func TestCommitmentProofHardening(...) {
     t.Run("verify with empty root", func() ... {
     })

     t.Run("verify row proof", func() ... {
     })
}
```

WDYT ?

File: blob/blob_fuzz_test.go [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+	"encoding/json"
+	"os"
+	"path/filepath"
+	"testing"
+
+	"github.com/celestiaorg/celestia-node/blob/blobtest"
+)
+
+func FuzzProofEqual(f *testing.F) {
+	if testing.Short() {
```
Comment (cristaloleg) [inline blob/blob_fuzz_test.go:13]: Why do we need skip this?

Comment (odeke-em) [reply blob/blob_fuzz_test.go:13]: It is customary to avoid running such long running operations when a user explicitly requests for go test -short

File: blob/commitment_proof.go (hunk 2 above)
Comment (odeke-em) [reply blob/commitment_proof.go:130]: There aren't identical, those are 2 different conditions in there when slicing commitmentProof.SubtreeRoots  that would cause 2 separate panics hence the different checks, please see the error messages for each and please see my break down:
1. `commitmentProof.SubtreeRoots[subtreeRootsCursor:]` <-- panic 1
2. `:subtreeRootsCursor+len(ranges)]` <-- panic 2

File: blob/repro_test.go (hunk 3 above)
Comment (odeke-em) [reply blob/repro_test.go:13]: I highly recommend keeping regression tests separate and isolated. Perhaps after this merge as the maintainers y'all can make the changes as you desire? But in my experience of dealing with a large amount of regressions and security+QA for large projections, best to always keep the tests as isolated as possible.

File: blob/blob_fuzz_test.go (hunk 4 above)
Comment (cristaloleg) [reply blob/blob_fuzz_test.go:13]: AFAIR fuzz test are run only with `-fuzz` flag, so user expects fuzzing to run.

File: blob/commitment_proof.go (hunk 2 above)
Comment (cristaloleg) [reply blob/commitment_proof.go:130]: Cool, thanks!

File: blob/repro_test.go (hunk 3 above)
Comment (cristaloleg) [reply blob/repro_test.go:13]: Disagree on "separate and isolated" but "can make the changes as you desire" sounds fair.

File: blob/blob_fuzz_test.go (hunk 4 above)
Comment (odeke-em) [reply blob/blob_fuzz_test.go:13]: -fuzz when ran manually takes only one fuzzing function, when you put it on oss-fuzz and other continuous fuzzers there are a variety of conditions and specifications on the commandline, one of which is -short

**Review by walldiss — APPROVED** [review]

**Review by vgonkivs — APPROVED** [review]

**Comment by Wondertan** [comment]
@odeke-em, do you mind fixing linter?

**Comment by Wondertan** [comment]
Hey @odeke-em. Thank you again for your contribution. We want to merge, but we can't until the linter is fixed. We can't push to your branch so we may do another PR cherry-picking your changes if you don't fix linter and rebase.

**Comment by odeke-em** [comment]
Thanks for the ping @Wondertan! I've made an update but I'd like to point out that maybe I am missing context but it is a mistake to prefer relative imports within the same package instead of the whole package: to make things work I had to make repro_test.go skip the absolute import which doesn't look right to make and makes it later cumbersome to copy and paste full working repros
```diff
diff --git a/blob/repro_test.go b/blob/repro_test.go
index 5489a6a4..42bd966f 100644
--- a/blob/repro_test.go
+++ b/blob/repro_test.go
@@ -4,13 +4,14 @@ import (
 	"testing"
 
 	"github.com/celestiaorg/celestia-app/v2/pkg/proof"
-	"github.com/celestiaorg/celestia-node/blob"
 	"github.com/celestiaorg/nmt"
 	"github.com/celestiaorg/nmt/pb"
 )
 
 // Reported at https://github.com/celestiaorg/celestia-node/issues/3731.
 func TestCommitmentProofRowProofVerifyWithEmptyRoot(t *testing.T) {
+	cp := &CommitmentProof{
-	cp := &blob.CommitmentProof{
 		RowProof: proof.RowProof{
 			Proofs: []*proof.Proof{{}},
 		},
@@ -23,7 +24,7 @@ func TestCommitmentProofRowProofVerifyWithEmptyRoot(t *testing.T) {
 
 // Reported at https://github.com/celestiaorg/celestia-node/issues/3730.
 func TestCommitmentProofRowProofVerify(t *testing.T) {
+	cp := &CommitmentProof{
-	cp := &blob.CommitmentProof{
 		RowProof: proof.RowProof{
 			Proofs: []*proof.Proof{{}},
 		},
@@ -36,7 +37,7 @@ func TestCommitmentProofRowProofVerify(t *testing.T) {
 // Reported at https://github.com/celestiaorg/celestia-node/issues/3729.
 func TestCommitmentProofVerifySliceBound(t *testing.T) {
 	proof := nmt.ProtoToProof(pb.Proof{End: 1})
+	cp := &CommitmentProof{
-	cp := &blob.CommitmentProof{
 		SubtreeRootProofs: []*nmt.Proof{
 			&proof,
 		},
@@ -48,7 +49,7 @@ func TestCommitmentProofVerifySliceBound(t *testing.T) {
 
 // Reported at https://github.com/celestiaorg/celestia-node/issues/3728.
 func TestCommitmentProofVerifyZeroSubThreshold(t *testing.T) {
+	cp := new(CommitmentProof)
-	cp := new(blob.CommitmentProof)
 	if _, err := cp.Verify(nil, 0); err == nil {
 		t.Fatal("expected a non-nil error")
 	}
@@ -56,8 +57,8 @@ func TestCommitmentProofVerifyZeroSubThreshold(t *testing.T) {
 
 // Reported at https://github.com/celestiaorg/celestia-node/issues/3727.
 func TestBlobUnmarshalRepro(t *testing.T) {
+	blob := new(Blob)
+	if err := UnmarshalJSON([]byte("{}")); err == nil {
-	blob := new(blob.Blob)
-	if err := blob.UnmarshalJSON([]byte("{}")); err == nil {
 		t.Fatal("expected a non-nil error")
 	}
 }
```

**Comment by Wondertan** [comment]
>  but it is a mistake to prefer relative imports within the same package instead of the whole package

@odeke-em, I highly doubt that unless you meant particularly for tests. For tests, yes, we could make every test file its own pkg `blob_test` instead of `blob` to enforce that, and it might be something we will do at some point, but currently, this is very far from our current prioritize and has low to no impact.

**Review by Wondertan — APPROVED** [review]

**Comment by Wondertan** [comment]
Well, linter is still failing

**Comment by odeke-em** [comment]
@Wondertan thanks for the review, kindly help me re-run the bots and all tests should pass now!

**Review by Wondertan — APPROVED** [review]

**Comment by odeke-em** [comment]
@Wondertan perhaps we have a test flake at https://github.com/celestiaorg/celestia-node/actions/runs/11126830327/job/30918109533?pr=3732
```shell
2024-10-01T14:05:14.951Z	ERROR	share/full	full/availability.go:71	availability validation failed	{"root": "94B65AB76ACAE0512B7A450F77110CD8CE25DD417ECDEDEE26814FAA2FEAF678", "err": "data not found\nread status from stream: protocols not supported: [/private/shrex/v0.1.0/eds_v0]\ndata not found\ncontext deadline exceeded\ncontext deadline exceeded"}
2024-10-01T14:08:14.972Z	ERROR	pruner/service	pruner/find.go:44	failed to get range from header store	{"from": 1024, "to": 1025, "error": "header/store: invalid range(1025,1024)"}
2024-10-01T14:08:15.044Z	ERROR	pruner/service	pruner/find.go:44	failed to get range from header store	{"from": 1024, "to": 1025, "error": "header/store: invalid range(1025,1024)"}
2024-10-01T14:08:15.102Z	ERROR	pruner/service	pruner/find.go:44	failed to get range from header store	{"from": 1024, "to": 1025, "error": "header/store: invalid range(1025,1024)"}
2024-10-01T14:08:15.116Z	ERROR	pruner/service	pruner/find.go:44	failed to get range from header store	{"from": 1024, "to": 1025, "error": "header/store: invalid range(1025,1024)"}
2024-10-01T14:08:15.191Z	ERROR	share/full	full/availability.go:71	availability validation failed	{"root": "94B65AB76ACAE0512B7A450F77110CD8CE25DD417ECDEDEE26814FAA2FEAF678", "err": "data not found\nopen stream: failed to negotiate protocol: protocols not supported: [/private/shrex/v0.1.0/eds_v0]\ndata not found\ncontext deadline exceeded\ncontext deadline exceeded"}
2024-10-01T14:14:15.236Z	ERROR	share/full	full/availability.go:71	availability validation failed	{"root": "94B65AB76ACAE0512B7A450F77110CD8CE25DD417ECDEDEE26814FAA2FEAF678", "err": "data not found\nopen stream: failed to negotiate protocol: protocols not supported: [/private/shrex/v0.1.0/eds_v0]\ndata not found\ncontext deadline exceeded\ncontext deadline exceeded"}
panic: test timed out after 20m0s
	running tests:
		TestArchivalBlobSync (20m0s)

goroutine 750540 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.23.1/x64/src/testing/testing.go:2373 +0x385
created by time.goFunc
	/opt/hostedtoolcache/go/1.23.1/x64/src/time/sleep.go:215 +0x2d

goroutine 1 [chan receive, 20 minutes]:
testing.(*T).Run(0xc0007ae000, {0x2fdd437?, 0x0?}, 0x384ea60)
	/opt/hostedtoolcache/go/1.23.1/x64/src/testing/testing.go:1751 +0x3ab
testing.runTests.func1(0xc0007ae000)
	/opt/hostedtoolcache/go/1.23.1/x64/src/testing/testing.go:2168 +0x37
testing.tRunner(0xc0007ae000, 0xc00129fc70)
	/opt/hostedtoolcache/go/1.23.1/x64/src/testing/testing.go:1690 +0xf4
testing.runTests(0xc000147158, {0x56acb00, 0x2, 0x2}, {0x475e90?, 0x475afa?, 0x57d7740?})
	/opt/hostedtoolcache/go/1.23.1/x64/src/testing/testing.go:2166 +0x43d
testing.(*M).Run(0xc0012da640)
	/opt/hostedtoolcache/go/1.23.1/x64/src/testing/testing.go:2034 +0x64a
main.main()
	_testmain.go:47 +0x9b

goroutine 5 [select, 20 minutes]:
github.com/desertbit/timer.timerRoutine()
	/home/runner/go/pkg/mod/github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:119 +0x9e
created by github.com/desertbit/timer.init.0 in goroutine 1
	/home/runner/go/pkg/mod/github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:15 +0x1a

goroutine 7 [select, 20 minutes]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0000c6420)
	/home/runner/go/pkg/mod/github.com/ipfs/go-log@v1.0.5/writer/writer.go:71 +0x105
created by github.com/ipfs/go-log/writer.NewMirrorWriter in goroutine 1
	/home/runner/go/pkg/mod/github.com/ipfs/go-log@v1.0.5/writer/writer.go:36 +0xbf

goroutine 20 [select]:
github.com/golang/glog.(*fileSink).flushDaemon(0x57d7958)
	/home/runner/go/pkg/mod/github.com/golang/glog@v1.2.1/glog_file.go:351 +0xb4
created by github.com/golang/glog.init.1 in goroutine 1
	/home/runner/go/pkg/mod/github.com/golang/glog@v1.2.1/glog_file.go:166 +0x126

goroutine 21 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0003bc200)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x9f
created by go.opencensus.io/stats/view.init.0 in goroutine 1
	/home/runner/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d

goroutine 23 [IO wait, 20 minutes]:
internal/poll.runtime_pollWait(0x7f417b662038, 0x72)
	/opt/hostedtoolcache/go/1.23.1/x64/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc0006c0880?, 0xc0005bdd50?, 0x0)
	/opt/hostedtoolcache/go/1.23.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.23.1/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadMsg(0xc0006c0880, {0xc0005bdd50, 0x10, 0x10}, {0xc0004f0c28, 0x1000, 0x1000}, 0x40000000)
	/opt/hostedtoolcache/go/1.23.1/x64/src/internal/poll/fd_unix.go:302 +0x385
net.(*netFD).readMsg(0xc0006c0880, {0xc0005bdd50?, 0x9?, 0x8d07000000?}, {0xc0004f0c28?, 0x3caae40?, 0x0?}, 0x1?)
	/opt/hostedtoolcache/go/1.23.1/x64/src/net/fd_posix.go:78 +0x31
net.(*UnixConn).readMsg(0xc00008a988, {0xc0005bdd50?, 0x41806b?, 0x7f[413](https://github.com/celestiaorg/celestia-node/actions/runs/11126830327/job/30918109533?pr=3732#step:4:414)49c12c8?}, {0xc0004f0c28?, 0xc0006ebdd0?, 0x472c1d?})
	/opt/hostedtoolcache/go/1.23.1/x64/src/net/unixsock_posix.go:115 +0x45
net.(*UnixConn).ReadMsgUnix(0xc00008a988, {0xc0005bdd50?, 0x30?, 0x50?}, {0xc0004f0c28?, 0x7f41349c12c8?, 0x18?})
	/opt/hostedtoolcache/go/1.23.1/x64/src/net/unixsock.go:143 +0x36
github.com/godbus/dbus.(*oobReader).Read(0xc0004f0c08, {0xc0005bdd50?, 0xc0006ebe30?, 0x413025?})
	/home/runner/go/pkg/mod/github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/transport_unix.go:21 +0x3c
io.ReadAtLeast({0x3c71c00, 0xc0004f0c08}, {0xc0005bdd50, 0x10, 0x10}, 0x10)
	/opt/hostedtoolcache/go/1.23.1/x64/src/io/io.go:335 +0x90
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.23.1/x64/src/io/io.go:354
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc000146e10)
	/home/runner/go/pkg/mod/github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/transport_unix.go:91 +0xfe
github.com/godbus/dbus.(*Conn).inWorker(0xc000611050)
	/home/runner/go/pkg/mod/github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/conn.go:294 +0x35
created by github.com/godbus/dbus.(*Conn).Auth in goroutine 1
	/home/runner/go/pkg/mod/github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/auth.go:118 +0x8ee
```

**Review by cristaloleg — APPROVED** [review]

**Comment by Wondertan** [comment]
@odeke-em, it is flaky, yes
